### ISSUE TITLE
Fixpoint parser produces a different result than liquid

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquid-fixpoint#101]
The `FInfo` that `fixpoint` produces when reading in a `.fq` file is not the same as the `FInfo` that `liquid` produces when reading in a `.hs` file. This is causing issues for many files in the `liquid` test suite.

Given the following input:

```
fixpoint +RTS -N4 -RTS --cores=4 ../liquidhaskell/tests/pos/.liquid/RBTree-col-height.hs.fq
```

A [massive error](https://gist.github.com/christetreault/b0c480b8efb70ae0e3fd#file-gistfile1-txt) is returned. 

Much discussion of this issue has happened in the thread for issue #90:

https://github.com/ucsd-progsys/liquid-fixpoint/issues/90#issuecomment-131186394 by Chris
 ... through ...
https://github.com/ucsd-progsys/liquid-fixpoint/issues/90#issuecomment-131921379 by Chris

**Comment by ranjitjhala** [comment]
@christetreault can you let me know if this issue still remains on the new `master` branch. (I did a bunch of changes to the parser/serializer that *should* have addressed this.)

**Comment by christetreault** [comment]
@ranjitjhala 

The follwing tests pass for me on the current fixpoint/liquid masters:

neg/pred.hs
neg/sumk.hs
crash/*
error/crash/*

All other tests fail with ExitCode 2, and I'm getting parser errors when running liquid manually

**Comment by christetreault** [comment]
Still no luck, now I get this:

```
$ fixpoint --cores=4 ../liquidhaskell/tests/pos/.liquid/RBTree-col-height.hs.fq
Liquid-Fixpoint Copyright 2009-13 Regents of the University of California.
All Rights Reserved.

Unexpected Error: ../liquidhaskell/tests/pos/.liquid/RBTree-col-height.hs.fq:406:21-406:21: Error: parseError "../liquidhaskell/tests/pos/.liquid/RBTree-col-height.hs.fq" (line 406, column 21):
unexpected "("
expecting ")"
 when parsing from ../liquidhaskell/tests/pos/.liquid/RBTree-col-height.hs.fq

EXIT: ExitFailure 2
```

At least the error is more useful!

**Comment by bmcfluff** [comment]
I think the problem is with type variable application (i.e. "@(0) @(1)") - see https://github.com/ucsd-progsys/liquid-fixpoint/issues/75#issuecomment-135568522 - I think that "step 4" does need to be implemented in the Haskell parser.

An example very small fq file that fails: https://github.com/ucsd-progsys/liquid-fixpoint/blob/8b3e1cbea6b089eea35d57505d7b89033c41b6c4/tests/todo/tvar-application.fq

**Comment by ranjitjhala** [comment]
Friends, please regenerate the .fq files from the .hs source because the format has changed a bit.

**Comment by bmcfluff** [comment]
I did regenerate from source earlier today, i.e. more recently than any commit to either master branch. I pushed the regenerated files to fixpoint master - do they look correct?

**Comment by christetreault** [comment]
I did as well, no change in behavior.

**Comment by ranjitjhala** [comment]
Thanks guys -- I'll fix this now.

**Comment by ranjitjhala** [comment]
@christetreault I fixed the parser (I think) can you let me know if this is still an issue? else we can close. Thanks!

**Comment by christetreault** [comment]
On it.

**Comment by christetreault** [comment]
@ranjitjhala: It works for the original file `RBTree-col-height.hs.fq` and the smallest broken file I identified `lit.hs`.

I vote this issue be closed.

**Comment by ranjitjhala** [comment]
sounds good. thanks!

On Thu, Sep 3, 2015 at 12:09 PM, Chris Tetreault <notifications@github.com>
wrote:

> @ranjitjhala <https://github.com/ranjitjhala>: It works for the original
> file RBTree-col-height.hs.fq and the smallest broken file I identified
> lit.hs.
>
> I vote this issue be closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/101#issuecomment-137544816>
> .
>



-- 
Ranjit.
