### ISSUE TITLE
Need --maxpartsize flag in fixpoint and liquid

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquid-fixpoint#104]
Suppose we set minpartsize=500 for some file. We then partition that file into 4 partitions, and we get the following sizes: 499, 500, 500, 500

At this point, `partitionN` will combine the two smallest partition into: 999, 500, 500, and the end result is we've turned 4 perfectly balanced partitions into 2 balanced, and one very unbalanced partitions.

We should add a `maxpartsize` flag such that the behavior of `partitonN` becomes:

1) `partitionN` will create `N` partitions, were `N = [cores flag value]`.
2) If `|partitions| <= 1` goto 6
3) if `|smallest partition| > |minpartsize|` goto 6
4) if `|smallest partition| + |second smallest partition| > |maxpartsize|` goto 6
5) combine the two smallest partitions, goto 2
6) done

**Comment by christetreault** [comment]
If accepted, liquid haskell pull request [#440](https://github.com/ucsd-progsys/liquidhaskell/pull/440) and fixpoint pull request #107 should close this issue.

**Comment by ranjitjhala** [comment]
looks like those PRs are merged, so is this closed?
