### ISSUE TITLE
"You probably have a stale fixpoint.native"

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquid-fixpoint#106]
The scenario: some new feature lands, and you want to try it out. Oh No! Calamity! Nothing works, it's all burning to the ground!

Hours later, it turns out that `fixpoint.native` decided not to rebuild itself, despite the fact that you recreated your sandbox and did a `cabal clean`.

Ideally, `fixpoint.native` would rebuilt itself when needed. However, if `cabal clean` would execute `cd external/fixpoint && make clean` and always build `fixpoint.native` in a new sandbox, that would be an improvement.

**Comment by ranjitjhala** [comment]
Thanks for adding this! We've been seeing a LOT of this. Oddly @gridaphobe did a bunch of work to fix this, I suspect it's a matter of making "build external" to default to TRUE when building in DEV mode as opposed to for a USER that is installing from cabal?

**Comment by gridaphobe** [comment]
Hooking into `cabal clean` would indeed be great. But it would be even better if someone could figure out why the ocaml build system decides not to rebuild fixpoint. We **always** call `make` in external/fixpoint as part of `cabal build`.

**Comment by ranjitjhala** [comment]
Yes, the Ocaml build system is rather vexing... Will have to fix it.

**Comment by ranjitjhala** [comment]
@gridaphobe how do you know that "the ocaml build system decides not to rebuild fixpoint" ? i.e. can you give some steps to reproduce? (The other option is to just NUKE the ocaml build system and use something more modern, assuming it exists?)

**Comment by gridaphobe** [comment]
I can't consistently reproduce the issue, but I know it has to be ocaml-related because `cabal build` unconditionally invokes `cd external/fixpoint && make`.

**Comment by christetreault** [comment]
Perhaps, as a stopgap until we have a good fix, we can have cabal build unconditionally invoke `cd external/fixpoint && make clean && make`?

**Comment by ranjitjhala** [comment]
I think that doesn't work because then you HAVE to have ocaml i.e. breaks
the "simple" `cabal install` case?


On Thu, Sep 3, 2015 at 12:06 PM, Chris Tetreault <notifications@github.com>
wrote:

> Perhaps, as a stopgap until we have a good fix, we can have cabal build
> unconditionally invoke cd external/fixpoint && make clean && make?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/106#issuecomment-137544176>
> .
>



-- 
Ranjit.

**Comment by christetreault** [comment]
...but isn't this already the case? Looking at the makefile, the default target is [all](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/Makefile#L49-L54) which seems to require ocamlbuild already.

If we're really supporting the no ocaml case, then perhaps whatever mechanism is responsible for this is the culprit and not ocamlbuild?

**Comment by gridaphobe** [comment]
By "unconditional" I meant it will always run `make` **if** you pass `-fbuild-external`, which is not the default for releases.

So @christetreault's suggestion would work.

**Comment by christetreault** [comment]
Fixpoint no longer uses the ocaml solver by default. Due to this, I no longer consider this to be an issue. If somebody wants to use the old solver, I think its reasonable that they should make sure it's rebuilt first.
