### ISSUE TITLE
Should we clean up old branches?

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#108]
There are 17 of them. At the very least, should we remove some of the following branches that have been fully merged into master?

bitvector
cores
list_parsing
smt-refactor
sorts
stats
tmp_fix1

(same goes even more so for liquidhaskell - 29 branches, with fully merged:

cores
cutsolver
ghc-7.10
non_applied_tycons
paths
pprinting
sorts
test-liquid-opts
tiny-travis-fix
travis_retry
type-class

)

**Comment by christetreault** [comment]
I can delete the cores branches. I was holding onto them "in case I need them", but I suppose that's just silly...

**Comment by ranjitjhala** [comment]
I have the same fear but best to delete after merging with master :)

**Comment by gridaphobe** [comment]
If a branch has been fully merged and you're done with it, you might as well delete it. No information will be lost..

**Comment by ranjitjhala** [comment]
Yes (delete them) thanks!

**Comment by bmcfluff** [comment]
Done
