### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#110]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/tests/todo/parse-tyfam0.fq

Haskell fixpoint cannot parse it

**Comment by ranjitjhala** [comment]
on it.

**Comment by ranjitjhala** [comment]
should be fixed by b99601a32696b9393dcddf9e3d39c5b317f0dc5d
