### ISSUE TITLE
Function equality

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#112]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tests/liquidhaskell_tests/pos/vector2.hs.fq#L723

z3 will not handle such refinements. Do we need to find a way to remove them, or does liquidhaskell need to find a way to stop generating them?

**Comment by bmcfluff** [comment]
Oh right, this is already logged as an LH bug

**Comment by ranjitjhala** [comment]
@bmcfluff -- which LH bug is this? I also see this in:

`external/fixpoint/tests/liquidhaskell_tests/pos/vecloop.hs.fq`

so am reopening for now.

@nikivazou why do we generate refinements over function symbols? 
Or is this just some unfortunate artifact of substitution? Or singletons `{v = x}` ?

**Comment by gridaphobe** [comment]
https://github.com/ucsd-progsys/liquidhaskell/issues/384 looks relevant

**Comment by ranjitjhala** [comment]
@bmcfluff can you check this is indeed fixed by PR https://github.com/ucsd-progsys/liquid-fixpoint/pull/115

**Comment by bmcfluff** [comment]
This is LH bug https://github.com/ucsd-progsys/liquidhaskell/issues/432

Checking PR #115 now...

**Comment by bmcfluff** [comment]
vector2.hs.fq now fails with a bunch of nested errors like "Multiple sorts for Data.Maybe.Nothing#r19 : [func(1, [(Data.Maybe.Maybe  @(0))]), function] "

**Comment by bmcfluff** [comment]
Here's a small example: https://github.com/ucsd-progsys/liquid-fixpoint/blob/02a9b46aa87bb0781489c74804fef6e9d94d839f/tests/todo/multiple-func-sorts.fq

Is this something that Uniqify needs to address - binds and constants with the same name?

**Comment by ranjitjhala** [comment]
1. Can you point to a concrete LH fq file in which the above happens? 
2. Is the sort given in the `constant` the same as that given in the `bind` -- if so, its fine, we can just not panic and move on. If the sorts are DIFFERENT that is definitely a hassle that needs to be dealt with in `uniqify`.

**Comment by bmcfluff** [comment]
1. https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tests/liquidhaskell_tests/pos/vector2.hs.fq lines 239 and 264

2. the sort is the same

**Comment by ranjitjhala** [comment]
ok, thats not problem -- I'll deal with it.

**Comment by bmcfluff** [comment]
Newest function-related error: https://github.com/ucsd-progsys/liquid-fixpoint/blob/d8f67b311de8b8815cdd0953624f3c54a61e4813/tests/todo/wrong-arity.fq

**Comment by ranjitjhala** [comment]
Definitely an LH bug @nikivazou

**Comment by ranjitjhala** [comment]
what are "foo" and "z" in the original vector2.hs.fq ?

​

**Comment by bmcfluff** [comment]
foo: fix#GHC.Types.#58##35#64
z: lq_anf__d2P1

**Comment by ranjitjhala** [comment]
well, the odd thing is that the original source ALSO has a:

constant fix#GHC.Types.#58##35#64 : (func(1, [@(0);
                                              [@(0)];
                                              [@(0)]]))

and if you add that back to your wrong-arity.fq then things seem to be
fine...

hmm.

​

**Comment by bmcfluff** [comment]
I did simplify the types involved, but the error is the same. It was remarkably fickle - seemingly irrelevant changes often made it disappear/reemerge. Whatever else it may be though, it's definitely also an LQ bug - fixpoint and fixpoint -n should not give different answers.

**Comment by ranjitjhala** [comment]
I think this has to do with uniqify. Note that the smt file contains BOTH
declarations:


(declare-fun lq_rnm_fixzhGHC.Types.zh58zhzh35zh64_72 () Int)


as well as:


(declare-fun fixzhGHC.Types.zh58zhzh35zh64 (Int Int) Int)

in general, why is this lq_rnm business being created? Thats whats causing
the problem.


On Thu, Sep 3, 2015 at 1:46 PM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> well, the odd thing is that the original source ALSO has a:
>
> constant fix#GHC.Types.#58##35#64 : (func(1, [@(0);
>                                               [@(0)];
>                                               [@(0)]]))
>
> and if you add that back to your wrong-arity.fq then things seem to be
> fine...
>
> hmm.
>
> ​
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
to be precise: why is THIS particular symbol -- which is in fact a CONSTANT
and should not be renamed, being renamed?
​

**Comment by bmcfluff** [comment]
Uniqify appears to be doing its job correctly: in the original vector2.hs.fq, fix#GHC.Types.#58##35#64 appears as bind 6 AND bind 72 (as well as a constant), so uniqify renames bind 72.

**Comment by ranjitjhala** [comment]
Reopened separate issue #119
