### ISSUE TITLE
String literal equality test

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#113]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/tests/todo/literals.fq

Ocaml says safe; Haskell says unsafe.

**Comment by ranjitjhala** [comment]
Fixed by above PR.

**Comment by bmcfluff** [comment]
Can't we have two constants of the same sort that might *not* be distinct?

**Comment by ranjitjhala** [comment]
well, the semantics of `constant` is that they are distinct (thats how they
are different from mere `bind`).
​
