### ISSUE TITLE
Floats

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#114]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/tests/todo/float.fq

Ocaml says safe; Haskell says unsafe.

**Comment by ranjitjhala** [comment]
Should be fixed by 4cb83f46e340c617be10bcb2a6e0244058207732.

@bmcfluff can you confirm and close?

**Comment by ranjitjhala** [comment]
I'm linking to the nearest commit but the stuff is in master already...

**Comment by bmcfluff** [comment]
Confirmed
