### ISSUE TITLE
Previously passing tests now fail with Unsafe

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#120]
For example:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tests/liquidhaskell_tests/pos/TopLevel.hs.fq

And while I don't have a small test case yet, I think I know why: look at lines 175 and 188 of that file; under the new scheme where binders that match a constant get dropped, we lose the refinement on bind 5 which may have been necessary to prove things Safe.

**Comment by ranjitjhala** [comment]
Hmm that seems odd -- what's an example binder / refinement that's getting dropped?

**Comment by ranjitjhala** [comment]
i get it, `True` is the constant/binder in question.

Hmm, let me think about this.
​

**Comment by ranjitjhala** [comment]
Seems to me that:

IF

  + you have a binder and constant with the same name `x`,

THEN

  + all the binders should have the same sort (of course)
  + all the binders should be free of any KVARs (only CONCRETE refinements)

In short we NEED NOT rename those binders, because there are no KVARs.

SO: can you modify uniqify (aka renameAll, so that it DOES NOT rename any
binders
that correspond to constants.)

Thanks!

RJ.


On Fri, Sep 4, 2015 at 11:20 AM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> i get it, `True` is the constant/binder in question.
>
> Hmm, let me think about this.
> ​
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
btw this might also be why vecloop.hs.fq fails, and so I'll wait for you to
finish.

On Fri, Sep 4, 2015 at 11:26 AM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> Seems to me that:
>
> IF
>
>   + you have a binder and constant with the same name `x`,
>
> THEN
>
>   + all the binders should have the same sort (of course)
>   + all the binders should be free of any KVARs (only CONCRETE refinements)
>
> In short we NEED NOT rename those binders, because there are no KVARs.
>
> SO: can you modify uniqify (aka renameAll, so that it DOES NOT rename any
> binders
> that correspond to constants.)
>
> Thanks!
>
> RJ.
>
>
> On Fri, Sep 4, 2015 at 11:20 AM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:
>
>> i get it, `True` is the constant/binder in question.
>>
>> Hmm, let me think about this.
>> ​
>>
>
>
>
> --
> Ranjit.
>



-- 
Ranjit.

**Comment by bmcfluff** [comment]
I think I finished; now I just need to revert your change that pruned binders matching constants, right?

**Comment by bmcfluff** [comment]
Fixed (hopefully) by 20860763c7d882b2357287351c55cd88770cb3be

**Comment by bmcfluff** [comment]
TopLevel is fixed but most others aren't - I'll find a new test case and open another issue.
