### ISSUE TITLE
non-constant function evaluation

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#121]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/31ae6c8466901cb87ef9a4445d10ca91c8db3949/tests/todo/wrong-arity2.fq

and the original file

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tests/liquidhaskell_tests/pos/ResolvePred.hs.fq

Is this a LH problem - there's a refinement that attempted to evaluate a non-constant function.

**Comment by ranjitjhala** [comment]
Hi Ben, can you post this as an issue on the liquid Haskell repo?

**Comment by bmcfluff** [comment]
Posted at https://github.com/ucsd-progsys/liquidhaskell/issues/443

Closing this issue since it's not a fixpoint issue.
