### ISSUE TITLE
Multiple sorts

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#126]
See:

https://raw.githubusercontent.com/ucsd-progsys/liquid-fixpoint/master/external/fixpoint/tests/liquidhaskell_tests/pos/RBTree-height.hs.fq

The _parser_ renames VV#F808 on line 70088 to VV#808. Then renameVV dumps it into the BindEnv, where it conflicts with the differently-sorted VV#808 on line 7872.

I'd like to discuss the purpose of renameVV (for starters, it doesn't rename anything) and how it interacts with Uniqify.

**Comment by ranjitjhala** [comment]
Eeks. Let's discuss tomorrow 1p?
Do you have a concrete proposal?

**Comment by bmcfluff** [comment]
1p works.

I think the simplest solution is to just move the Uniqify pass after the renameVV pass. A more extreme solution - if we're treating the VV of a constraint so much like a binder anyway, could we replace the whole {lhs :: SortedReft, rhs :: SortedReft} system with just {rhs :: Pred}?

**Comment by bmcfluff** [comment]
Fixed by #132
