### ISSUE TITLE
Bug in sort checking 

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquid-fixpoint#131]
If you run 

`fixpoint.native -v 1  -notruekvars -refinesort -nosimple -strictsortcheck -sortedquals -no-gen-qual-sorts -smtsolver z3  tests/Poly1.fq`

on the following file

[tests/Poly1.fq](https://github.com/ucsd-progsys/liquid-fixpoint/blob/bc544432e70bc6ef80407c86defe7b3197237e97/external/fixpoint/tests/Poly1.fq)

you get an error (`Z3RelTypeError`) as `sortcheck_pred` of `v = append([Nil; v])` returns `false`.

I will update the sort checker so that the above example passes.

**Comment by ranjitjhala** [comment]
@nikivazou is this the thing that you are working on (in the other branch?) I seem to recall some mail about improved sort checking/unification?

**Comment by nikivazou** [comment]
@ranjitjhala this is what I am working on (but on master, no other branch)

**Comment by ranjitjhala** [comment]
hmm. was there a good reason to not be on a branch? (Working with master
has always been dangerous for me...)

On Monday, September 14, 2015, Niki Vazou <notifications@github.com> wrote:

> @ranjitjhala <https://github.com/ranjitjhala> this is what I am working
> on (but on master, no other branch)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/131#issuecomment-140228632>
> .
>


-- 
Ranjit.

**Comment by ranjitjhala** [comment]
@nikivazou is this fixed by your recent edits?

**Comment by nikivazou** [comment]
Yes, but still haven't checked if my new implementation slows down liquidHaskell.

**Comment by ranjitjhala** [comment]
ah ok. is your new thing on a branch or master (of liquid-fixpoint?)


On Wednesday, September 16, 2015, Niki Vazou <notifications@github.com>
wrote:

> Yes, but still haven't checked if my new implementation slows down
> liquidHaskell.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/131#issuecomment-140925901>
> .
>


-- 
Ranjit.

**Comment by nikivazou** [comment]
master

**Comment by nikivazou** [comment]
But you need a flag "-newcheck" to activate it

**Comment by ranjitjhala** [comment]
--newcheck when running `liquid` right?

e.g. `liquid --newcheck foo.hs`

?

On Wednesday, September 16, 2015, Niki Vazou <notifications@github.com>
wrote:

> But you need a flag "-newcheck" to activate it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/131#issuecomment-140926453>
> .
>


-- 
Ranjit.

**Comment by nikivazou** [comment]
Yes.

**Comment by ranjitjhala** [comment]
I am seeing a bit of slowdown on RBTree-ord.hs.

   19s --> 24s

re-running a few times to double check.

PS: @nikivazou -- can you please come on the SLACK thing.
Somehow I find it a *LOT* more convenient for discussing
LH/Fixpoint etc. than email.

>
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/131#issuecomment-140930679>
> .
>


-- 
Ranjit.

**Comment by christetreault** [comment]
I just tested on benchmarks test and bytestring. Seeing roughly the same times on both for single and 4 cores.

**Comment by christetreault** [comment]
I just tested on benchmarks test and bytestring. Seeing roughly the same times on both for single and 4 cores. Maybe a few seconds slower than the results I posted on Slack on the 10th.

**Comment by ranjitjhala** [comment]
Its probably fine to make `--newcheck` the default:


time stack exec -- liquid --cores=1 --newcheck -i
benchmarks/bytestring-0.9.2.1/
benchmarks/bytestring-0.9.2.1/Data/ByteString.hs

      277.49 real       233.65 user         5.14 sys

time stack exec -- liquid --cores=1 -i benchmarks/bytestring-0.9.2.1/
benchmarks/bytestring-0.9.2.1/Data/ByteString.hs

      269.99 real       220.64 user         6.18 sys

I guess 7 / 270 s is not the worst thing. (OTOH 3/20 is not so great
either.)

rjhala@borscht ~/r/s/l/liquidhaskell (master)> time stack exec -- liquid
--cores=1 tests/pos/RBTree-ord.hs

       22.85 real        15.06 user         1.72 sys

rjhala@borscht ~/r/s/l/liquidhaskell (master)> time stack exec -- liquid
--cores=1 --newcheck tests/pos/RBTree-ord.hs

       23.46 real        18.11 user         1.27 sys


-- 
Ranjit.

**Comment by nikivazou** [comment]
I noticed too the small slow-down and I am trying to fix it, by changing my substitution structure from a list to a map.

**Comment by nikivazou** [comment]
I made my edit and time got a little better, so we can make the new check the default. 

Btw, what is the proper way to debug in ocaml? Now I am using just printing:

(* let logf s = print_string ("\nLOG: " ^ s) *) (* to turn debuggin on *) 
let logf s = ()

But even when I have it off, due to eagerness and if this is not optimized, the arguments of `logf`are evaluated, meaning many useless string concatenations happen.

**Comment by ranjitjhala** [comment]
I've been using a top-level `mydebug` at the start of each module, and then
guarding
the debug statements with them, e.g.

    let _  = if mydebug then (Printf.printf "[%d] UNSAT 1 " (us_ref += 1);
flush stdout) in

or

    let _  = Co.bprintflush mydebug "\nDONE: Fixpoint: Trueing
Unconstrained Variables \n" in





On Thursday, September 17, 2015, Niki Vazou <notifications@github.com>
wrote:

> I made my edit and time got a little better, so we can make the new check
> the default.
>
> Btw, what is the proper way to debug in ocaml? Now I am using just
> printing:
>
> (* let logf s = print_string ("\nLOG: " ^ s) *) (* to turn debuggin on *)
> let logf s = ()
>
> But even when I have it off, due to eagerness and if this is not
> optimized, the arguments of logfare evaluated, meaning many useless
> string concatenations happen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/131#issuecomment-141172993>
> .
>


-- 
Ranjit.

**Comment by nikivazou** [comment]
It got a littler faster! I am setting the new check as default in liquidhaskell

**Comment by ranjitjhala** [comment]
Nice! Thanks!

On Thu, Sep 17, 2015 at 7:52 PM, Niki Vazou <notifications@github.com>
wrote:

> It got a littler faster! I am setting the new check as default in
> liquidhaskell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/131#issuecomment-141327341>
> .
>



-- 
Ranjit.
