### ISSUE TITLE
Malformed WfC?

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#133]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tests/liquidhaskell_tests/pos/absref-crash0.hs.fq#L1789

Ocaml accepts it, but Haskell - I would think correctly - rejects these WfCs as malformed.

**Comment by ranjitjhala** [comment]
Will look at this tomorrow -- but it might be good if @nikivazou can also take a quick look she may be able to respond before me.

**Comment by nikivazou** [comment]
I do not see anything wrong with this constraint. 

Given the environment 

```
papp2        : (func(4, [(Pred  @(0)  @(1)); @(2); @(3); bool]))
VV           : b_aM4
lq_tmp_x_233 : {VV#28 : (Foo.List  a_aM3) | [$k__29]}
p            : {VV#239 : (Pred  b_aM4  (Foo.List  a_aM3)) | []}
```

Then 
```
? papp2(p, VV, lq_tmp_x_233)
```

is a valid `bool` expression

**Comment by bmcfluff** [comment]
One thing I'm missing is what is the purpose of a wf constraint that contains no kvar?

**Comment by ranjitjhala** [comment]
That is puzzling, but not totally unexpected because it can arise from
"splitting" a more complex refinement type.

Is that why its rejected? (assuming the reft is well-formed -- i.e.
typechecks, we can just DELETE
the WFC)



On Friday, September 11, 2015, bmcfluff <notifications@github.com> wrote:

> One thing I'm missing is what is the purpose of a wf constraint that
> contains no kvar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/133#issuecomment-139610741>
> .
>


-- 
Ranjit.

**Comment by nikivazou** [comment]
Yes, constraints without kvars seem meaningless but no wrong or malformed. So you should just ignore them,  but do not reject.

**Comment by ranjitjhala** [comment]
Is this fixed yet? If not shall I do it?

**Comment by bmcfluff** [comment]
Fixed by 25a19bdc7a483092cb3f9fc7332f566f9fd6f5e5

**Comment by ranjitjhala** [comment]
Do the failing tests now pass?

**Comment by bmcfluff** [comment]
Yes - the only LH.fq pos tests to fail now are 

pair00.hs.fq
pair0.hs.fq
maps1.hs.fq
maps.hs.fq
eqelems.hs.fq
