### ISSUE TITLE
Unknown constant / Bogus substitution Remix

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#134]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tests/liquidhaskell_tests/pos/pair00.hs.fq#L247

Like #68 except this time in the problematic substitution "$k__371[VV#380:=lq_tmp_x_401]", VV#380 _is_ in the domain of the kvar yet lq_tmp_x_401 does not exist.

**Comment by ranjitjhala** [comment]
I *suspect* this is a malformed constraint due to some abstract-refinement parameter hassles in LH.

paging @nikivazou ?

**Comment by nikivazou** [comment]
I suspect the same. Will take a look soon.

**Comment by bmcfluff** [comment]
Things have changed so here's the new version:

See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/36419b5a67fcda119f23865ca64d84b7988e80fe/tests/todo/pair00.hs.fq#L168

Like #68 except this time in the problematic substitution "$k__383[VV#382:=lq_tmp_x_400]", VV#382 is in the domain of the kvar yet lq_tmp_x_400 does not exist.

**Comment by nikivazou** [comment]
Thanks! I will take a look soon:)

**Comment by nikivazou** [comment]
Should be fixed by ucsd-progsys/liquidhaskell#485
