### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#135]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/9885756db01815a4457ac4a4725a82f870aabe4c/tests/todo/maps1.hs.fq

Haskell solver must never have been taught the dark secrets Ocaml knows about the theory of Maps (similar to #83).

**Comment by ranjitjhala** [comment]
Yes , this is easy...

**Comment by ranjitjhala** [comment]
1. Look at `external/fixpoint/{smtLIB2, theories.ml}` and make the corresponding addition in `Theories.hs`
2. See the corresponding  thing for `smt_set_*` and
3. Make the relevant additions for `smt_map_*`.

**Comment by bmcfluff** [comment]
Fixed by 8b8d497

**Comment by ranjitjhala** [comment]
Nice!! Thanks!
