### ISSUE TITLE
Qualifier Instantiation Error 2

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#136]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/005375839668a961b38574ae0a5c73d6277cfe37/tests/todo/qualif-inst.fq

Works with fixpoint but not fixpoint -n (related to #119?).

**Comment by bmcfluff** [comment]
Note: to reproduce this bug, you now need to remove line 12 ("grd true") from the linked fq file.

**Comment by ranjitjhala** [comment]
This test works fine now, added to `tests/pos/qualif-inst.fq`,
