### ISSUE TITLE
Bot by default?

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#137]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/63a8e62e17455ca86c24f4c074742fb1d2218924/tests/todo/bot.fq

fixpoint accepts this even though there is no explicit Bot qualifier, presumably because of a special case for unconstrained kvars. Do we want to add this behavior to fixpoint -n?

**Comment by nikivazou** [comment]
Do you have any qualifiers at all?

Even though there is no explicit Bot qualifier the `$k0` will most probably be initialized to something containing a contradiction, like `v > 0 & v < 0`.

**Comment by bmcfluff** [comment]
Another test involving multiple kvars:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/447d69161241a549bd56431766bca18ab0a7df53/tests/todo/bot2.fq

Same behavior.

**Comment by nikivazou** [comment]
These is an (efficiency) optimization in native fixpoint that says that, 

if there are unconstraint kvars in the environment of a constraint, then ignore the constraint. 

This is true assuming that bot is a qulifier: the unconstraint kvar will be false and the contraint will be trivially satisfied, as false is in the environment. 

At liquidHaskell, and because of this optimization, we require that bot is a qualifier, see 

https://github.com/ucsd-progsys/liquidhaskell/blob/master/include/Prelude.hquals#L1

**Comment by ranjitjhala** [comment]
Sure, but I think its fine to leave the current behavior for --native,
because its "sound".


On Wednesday, September 16, 2015, Niki Vazou <notifications@github.com>
wrote:

> These is an (efficiency) optimization in native fixpoint that says that,
>
> if there are unconstraint kvars in the environment of a constraint, then
> ignore the constraint.
>
> This is true assuming that bot is a qulifier: the unconstraint kvar will
> be false and the contraint will be trivially satisfied, as false is in the
> environment.
>
> At liquidHaskell, and because of this optimization, we require that bot is
> a qualifier, see
>
>
> https://github.com/ucsd-progsys/liquidhaskell/blob/master/include/Prelude.hquals#L1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/137#issuecomment-140833947>
> .
>


-- 
Ranjit.

**Comment by ranjitjhala** [comment]
same behavior == UNSAT right?


On Wednesday, September 16, 2015, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> Sure, but I think its fine to leave the current behavior for --native,
> because its "sound".
>
>
> On Wednesday, September 16, 2015, Niki Vazou <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> These is an (efficiency) optimization in native fixpoint that says that,
>>
>> if there are unconstraint kvars in the environment of a constraint, then
>> ignore the constraint.
>>
>> This is true assuming that bot is a qulifier: the unconstraint kvar will
>> be false and the contraint will be trivially satisfied, as false is in the
>> environment.
>>
>> At liquidHaskell, and because of this optimization, we require that bot
>> is a qualifier, see
>>
>>
>> https://github.com/ucsd-progsys/liquidhaskell/blob/master/include/Prelude.hquals#L1
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/137#issuecomment-140833947>
>> .
>>
>
>
> --
> Ranjit.
>
>

-- 
Ranjit.

**Comment by bmcfluff** [comment]
yes, same behavior is UNSAT for fixpoint -n and SAT for fixpoint

**Comment by nikivazou** [comment]
It is fine.

But, fixpoint is "sound" because it assumes that the bot qualifier is there.

**Comment by ranjitjhala** [comment]
@nikivazou you mean fixpoint-ocaml, right?

**Comment by nikivazou** [comment]
Right

On Wed, Sep 16, 2015 at 4:25 PM, Ranjit Jhala <notifications@github.com>
wrote:

> @nikivazou <https://github.com/nikivazou> you mean fixpoint-ocaml, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/137#issuecomment-140924770>
> .
>



-- 
Niki Vazou
