### ISSUE TITLE
Cabal file versioning needs to be maintained

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquid-fixpoint#144]
Same issue as: https://github.com/ucsd-progsys/liquidhaskell/issues/461: we have no dependency upper or lower bounds in `liquid-fixpoint.cabal`. The result will be cabal-install thinking it can just install any version of said dependencies. This will stop being a good plan as we try to build older and older versions of fixpoint.

This is less pressing than the above referenced issue though, because fixpoint doesn't depend on a non-hackage project, so there should be less random breakages. That said, the current state of affiars is "bad" and we should fix it.

**Comment by christetreault** [comment]
From where I'm sitting, this is a back burner issue. I'll fix it when I find some downtime, but feel free to take ownership if you're bored and want to fight with cabal!

**Comment by ranjitjhala** [comment]
I'm closing this, since I don't know what a concrete action item is...
