### ISSUE TITLE
Parsing

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#151]
If you run `liquid --native` on LH's `tests/pos/transpose.hs` it fails, but if you run `liquid` and then `fixpoint --native` on the resulting fq file, it passes.

**Comment by ranjitjhala** [comment]
@bmcfluff I *think* I have fixed this. Can you check using the `binary` branch? (Or I can merge into master too...).

Also: how do you run the `--native` regressions?

**Comment by bmcfluff** [comment]
This one is fixed.

Currently I run the `--native` regressions by swapping in (one line changes from my git stash) versions of `Liquid.hs` and fixpoint's `Interface.hs` that effectively hardwire the native flag, then running the standard test suite.

**Comment by bmcfluff** [comment]
Same symptoms, except for AVLRJ.hs and zipper.hs instead of transpose.hs.

**Comment by bmcfluff** [comment]
After those, only 4 other unit tests fail - Class.hs (reason as yet unknown), and 3 due to issues #134 and #136

**Comment by ranjitjhala** [comment]
Can we close this issue?
