### ISSUE TITLE
binders with different sorts

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquid-fixpoint#159]
@nikivazou and @bmcfluff see 

`tests/todo/Class0.fq` which is a distillation of `tests/todo/Class.hs.fq` which is from `tests/pos/Class.hs`.

It works with OCAML but not `--native` -- seems to have to do with the binders appearing under DIFFERENT sorts...?

**Comment by bmcfluff** [comment]
Fixed by 5c880b5

**Comment by ranjitjhala** [comment]
nice!
