### ISSUE TITLE
Liquid Haskell fails on integer literals greater than or equal to 0x4000000000000000

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquid-fixpoint#162]
Minimal reproducing program:

```haskell
-- example.hs

h :: Integer
h = 0x4000000000000000
```

... fails with:

```bash
$ liquid example.hs
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.


**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  generateConstraints ************************************************
 

**** START: fixpoint ***********************************************************
 


========================================================
© Copyright 2009 Regents of the University of California.
All Rights Reserved.
========================================================
safe_int_of_string crashes on: 4611686018427387904 (error = Failure("int_of_string"))Fatal error: exception Failure("int_of_string")

**** DONE:  fixpoint ***********************************************************
 

**** DONE:  solve **************************************************************
 

**** DONE:  annotate ***********************************************************
 

**** ERROR: Unknown Error ******************************************************
```

The same program succeeds if you decrement the integer to `0x3FFFFFFFFFFFFFFF`.

I filed this against the `liquid-fixpoint` repository because relevant code seems to be located here:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/154dff9329a23d38869f5fc47dc7ac80c0fd870d/external/fixpoint/fixLex.mll#L53

**Comment by ranjitjhala** [comment]
Yikes, thanks! Will look into this asap! (Also: need to check if the shiny new Haskell solver suffers similarly...)

**Comment by Gabriel439** [comment]
For anybody else that has this issue, you can work around this by building the larger literal from two smaller literals, like this:

````haskell
-- example.hs

h :: Integer
h = 0x2000000000000000 + 0x2000000000000000
```

**Comment by ranjitjhala** [comment]
Oh, thats I nice workaround -- thanks!

On Sat, Dec 5, 2015 at 2:47 PM, Gabriel Gonzalez <notifications@github.com>
wrote:

> For anybody else that has this issue, you can work around this by building
> the larger literal from two smaller literals, like this:
>
> -- example.hs
> h :: Integer
> h = 0x2000000000000000 + 0x2000000000000000
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/162#issuecomment-162254668>
> .
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
Looks like this works (and probably has for a while!) worked fine ever since we switched to the native haskell solver. Thanks!

**Comment by Gabriel439** [comment]
Thank you! :)
