### ISSUE TITLE
Fixpoint parser error with rhs conjunction (no kvars)

### ISSUE THREAD

**Issue by abakst** [ucsd-progsys/liquid-fixpoint#165]
`fixpoint` returns an error parsing the following:

https://gist.github.com/abakst/1756c428ae6da193a61b#file-foo-fq

`fixpoint: Error {errLoc = SS {sp_start = "ping.fq" (line 2, column 3), sp_stop = "ping.fq" (line 7, column 1)}, errMsg = "RHS without single conjunct at \"ping.fq\" (line 7, column 1) \n"}`

**Comment by ranjitjhala** [comment]
closed by https://github.com/ucsd-progsys/liquid-fixpoint/pull/166

**Comment by ranjitjhala** [comment]
@abakst can you check the above works for your actual test? thanks!

**Comment by abakst** [comment]
That fixes the parse error, thanks!
