### ISSUE TITLE
Different output for fixpoint and fixpoint.native

### ISSUE THREAD

**Issue by abakst** [ucsd-progsys/liquid-fixpoint#167]
Running `fixpoint` on https://gist.github.com/abakst/73c8955562b8ca67938a#file-ping_loop-fq returns `Unsafe` whereas `fixpoint.native` returns `SAT`.

**Comment by bmcfluff** [comment]
This is because the Haskell solver renames many things and so it does not play nicely with qualifiers containing unbound variables. Of course if you just add the extra parameters to Inv in this example then we have to instantiate a terrifying 8-place qualifier...

**Comment by ranjitjhala** [comment]
Actually if you split those conjunctions it's not so bad. 

In short no free variables in qualifiers please...

**Comment by abakst** [comment]
Hm...I guess I don't have an argument except that free variables are sometimes convenient for testing. Fine.

**Comment by ranjitjhala** [comment]
@bmcfluff -- we should probably add a sanitize check that complains about free variables in qualifiers, to avoid this confusion later.
