### ISSUE TITLE
Fixpoint hangs indefinitely on LH test file pos/Product.hs

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquid-fixpoint#173]
Fixpoint hangs indefinitely when solving https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/Product.hs via Liquid Haskell.

This occurs only when solving on Linux using Z3 4.4.0 (can be reproduced on goto), it works as advertised on my Mac running this same version of Z3.

@ranjitjhala has opened [an issue against Z3](https://github.com/Z3Prover/z3/issues/399) regarding this.

The output (until Z3 hangs) of solving this file can be found at: https://gist.github.com/christetreault/7571f4f2a3bd783df23f

**Comment by ranjitjhala** [comment]
The fix is to change:

```
(define-fun Z3_OP_MUL ((x Real) (y Real)) Real (* x y))
```

to 

```
(define-fun Z3_OP_MUL ((x Int) (y Int)) Int (* x y))
```

Aside: please don't use `Z3` when we mean `SMT` (as in this case).

Of course, if we actually need `Real` then we are overloading `+` and `*` etc. so may need
to define multiple SMT operators, and use the appropriate one at the given context...

**Comment by ranjitjhala** [comment]
Fixed, should have marked the PR...! Can you confirm?

**Comment by christetreault** [comment]
This has been working for me for a few weeks now, so it should be good to go!
