### ISSUE TITLE
Fixpoint Diverges on malformed smt queries

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquid-fixpoint#187]
On the [divergence](https://github.com/ucsd-progsys/liquid-fixpoint/tree/divergence) branch, `fixpoint --eliminate tests/pos/test000.hs.fq` diverges.

The reason is that 

 - serialize calls [sortExpr](https://github.com/ucsd-progsys/liquid-fixpoint/blob/divergence/src/Language/Fixpoint/SortCheck.hs#L89) 

- `sortExpr` fails, because [serialization of existentials](https://github.com/ucsd-progsys/liquid-fixpoint/blob/divergence/src/Language/Fixpoint/Smt/Serialize.hs#L117) does not insert the existential binders in the `sortExpr` environment

But instead of `sortExpr` crashing with an error, fixpoint diverges. Precisely, the [environment lookup](https://github.com/ucsd-progsys/liquid-fixpoint/blob/divergence/src/Language/Fixpoint/SortCheck.hs#L95) can trace that the look up will fail with `Nothing` but the `errorstar` is not called.

Although this behavior is not exposed to the end users, as all smt queries should be well formed, it makes debugging really difficult.

**Comment by gridaphobe** [comment]
Can you run with profiling and `-xc` to confirm that `errorstar` is not called? I find that hard to believe..

**Comment by nikivazou** [comment]
Thanks!!!!! problem solved!
