### ISSUE TITLE
Ill-sorted Constraints

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquid-fixpoint#189]
We should reject (with some sort of ERROR/CRASH) 

   `tests/todo/wl01.hs` (in the `graphs` branch ATM).

which has an ill-sorted constraint (with a variable not bound in the environment.)

I suspect it slips through as the variable _is_ in the global binder environment, so it somehow
sneaks past the sort checks (done with the global env.)

**Comment by bmcfluff** [comment]
Fixed by 74f39e0

**Comment by ranjitjhala** [comment]
Is this fixed?

**Comment by bmcfluff** [comment]
I believe that 74f39e0 fixed it.
