### ISSUE TITLE
Bug in SMT embedding of polymorphic applications

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquid-fixpoint#193]
@nikivazou there is some issue in your defunctionalization, see:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/tests/todo/poly.fq

which is just:

```
// MONOMORPHIC This definition works fine ...
// constant offset : (func(2, [int ; (BitVec Size32) ]))

// POLYMORPHIC But this crashes as 'offset 0' is embedded as int not bv...
constant offset : (func(2, [int; @(1)]))

bind 0 x  : {VV : (BitVec  Size32) | [ VV = offset 0 ]}

constraint: 
  env [0]
  lhs {VV : (BitVec Size32) | [ VV = x ] }
  rhs {VV : (BitVec Size32) | [ VV = x ] }
  id 1 tag [1]
```

The *monomorphic* definition works fine, but the *polymorphic* one doesn't, because the `offset 0` 
term gets embedded/serialized as `int` using the `int_apply`. This is a bug because the term is infact a `BitVec...` as thats the only way that the equality could be well-typed.

**Comment by nikivazou** [comment]
Pushed a fix!

**Comment by ranjitjhala** [comment]
is the `elaborate` code fixed and merged in? if so, shall we close this issue?

**Comment by nikivazou** [comment]
Yes, it is fixed, closing!
