### ISSUE TITLE
cannot build on windows

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquid-fixpoint#211]
The fancy new progress bar incurs a transitive dependency on unix, which means fixpoint won't build on windows anymore. Perhaps we can conditionally include the ascii-progress package on unix systems.

**Comment by ranjitjhala** [comment]
Do you know how to do that? Or is this cpp hell?

**Comment by gridaphobe** [comment]
Yes, but it will involve CPP :(

**Comment by ranjitjhala** [comment]
Btw, it says [here](https://hackage.haskell.org/package/unix) that the package is supported under cygwin.

Is cygwin dead / a non-starter these days?

**Comment by gridaphobe** [comment]
I don't think it's either, but supporting cygwin isn't the same as supporting windows. E.g. the recommended way of installing stack/ghc doesn't include cygwin, and you can build most haskell packages (including the hackage release of LH) without cygwin.

**Comment by gridaphobe** [comment]
Actually we might be able to remove the progress bar on windows without resorting to CPP, if we 

1. make a copy of the progress-bar module with stub functions
2. put this module in a separate directory
3. tell cabal to add this directory to the import path if on windows

I use this trick in LH to override the Paths_liquidhaskell module when developing.

**Comment by ranjitjhala** [comment]
that sounds crafty (should be super easy, just replace all functions with

  `return ()`

I think they are mostly of type `IO ()`
