### ISSUE TITLE
Fail more gracefully if z3 isn't working

### ISSUE THREAD

**Issue by spinda** [ucsd-progsys/liquid-fixpoint#231]
See https://github.com/spinda/liquidhaskell-cabal/issues/3

**Comment by ranjitjhala** [comment]
@spinda  is the issue that `fixpoint` keels over and dies with this odd `fd:hGetLine` error instead of saying "I cannot find Z3" or some such?

**Comment by gridaphobe** [comment]
That seems to be the issue. We already have a nice error message for when we **can't find** z3, but we don't check whether z3 is working properly.

**Comment by ranjitjhala** [comment]
what do you mean by "working properly" ?

**Comment by gridaphobe** [comment]
Something along the lines of: able to start-up and answer queries without crashing. As I understand it, in the referenced issue, `z3` was on the PATH and executable, but somehow mis-configured or mis-compiled. So it quickly crash, which presented to us as the pipe mysteriously vanishing.

I think the best we can do here is to watch out for such abnormal behavior of z3, and issue a general "Something appears to be wrong with z3" error.

**Comment by spinda** [comment]
I think a large part of the problem is that liquid-fixpoint reads from z3's stdout in many places without doing any error checking. At minimum, `smtReadRaw` should watch for EOF and throw up a proper error message if it hits it. z3's stderr output should also probably be logged instead of thrown away as it is now. Maybe it could be printed to the user as part of the error condition, similar to how Stack dumps the last N lines of GHC output on compilation failure.
