### ISSUE TITLE
Filenames in multiple places

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#238]
[Config stores source filenames](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Types/Config.hs#L45-47). [FInfo also stores them](https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Types/Constraints.hs#L454). Can we remove one of these two? It's causing confusion in for example [Minimize](https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Minimize.hs#L61-62).

**Comment by bmcfluff** [comment]
(Or if not remove one, at least add documentation on the purpose of each)

**Comment by ranjitjhala** [comment]
This would be a good idea, but its tricky. See if you can figure it out...
