### ISSUE TITLE
Elaborator Crash: Cannot unify (List.List  @(47)) with b_aebs

### ISSUE THREAD

**Issue by atondwal** [ucsd-progsys/liquid-fixpoint#267]
on cse230WI15 final exam's List.lhs

```
± stack exec fixpoint ~/src/liquidhaskell-study/wi15/.liquid/List.lhs.fq


Liquid-Fixpoint Copyright 2013-15 Regents of the University of California.
All Rights Reserved.


**** DONE:  Uniqify & Rename ***************************************************
 
solution:
fromList []
Crash!: :1:1-1:1: Error
  elaborate failed on:
      size lq_anf$##1677782276##dfME == size ds_dfIO
      && 0 <= size lq_anf$##1677782276##dfME
      && 0 <= sizes lq_anf$##1677782276##dfME
      && lq_anf$##1677782276##dfME == ds_dfIP
      && 0 <= size lq_anf$##1677782276##dfME
      && 0 <= sizes lq_anf$##1677782276##dfME
      && size lq_anf$##1677782276##dfME == 0
      && sizes lq_anf$##1677782276##dfME == 0
      && lq_anf$##1677782276##dfME == List.Emp##raQO
      && size lq_anf$##1677782276##dfME == 0
      && sizes lq_anf$##1677782276##dfME == 0
      && 0 <= size lq_anf$##1677782276##dfME
      && 0 <= sizes lq_anf$##1677782276##dfME
  with error
      Cannot unify (List.List  @(47)) with b_aebs in expression: sizes lq_anf$##1677782276##dfME
  in environment
      List.Emp##raQO := func(1, [(List.List  @(0))])

      lq_anf$##1677782276##dfME := (List.List  b_aebs)

      sizes := func(1, [(List.List  (List.List  @(0))); int])

      size := func(1, [(List.List  @(0)); int])

      ds_dfIO := (List.List  a_aebr)

      ds_dfIP := (List.List  b_aebs)
-> [2]
```

**Comment by nikivazou** [comment]
The error is legit!  These two types cannot be unified. 
What is the .fq file that creates it?

**Comment by atondwal** [comment]
[List.lhs.fq](https://github.com/ucsd-progsys/liquid-fixpoint/files/530473/List.lhs.fq.txt). It's generated from a skeleton from last year's CSE230 Final, so it shouldn't crash the elaborator (and presumably didn't at some point!)

**Comment by nikivazou** [comment]
During last year's CSE230 Final we did not have elaboration. 
The elaborator checks well formedness of intermediate logical expressions that were not checked before. So, I bet your .fq file leads to intermediate malformed expressions.

**Comment by atondwal** [comment]
Hmm, can a hs file that used to be safe generate an fq that causes an elaborator crash due to ill-formed intermediate expressions? I'm getting this error on even the safe (student homework) files in the 230 dataset from Eric --- I filed this bug about the skeleton because I didn't want to post the student solutions online.

It's right to point out that these types can't be unified, but I'm not sure why it's trying to unify these types, and I don't think it should be...

**Comment by ranjitjhala** [comment]
This is not impossible... (and there is good reason for it).

Can you post the file somewhere?

**Comment by atondwal** [comment]
So this is problem not just in the student solutions, but also in the original skeleton code (https://github.com/ucsd-progsys/liquidhaskell-study/blob/master/wi15/List.lhs).

Anyways, seems like we should move this to liquidhaskell, as it's not a bug in fixpoint, rather, liquid haskell shouldn't give us ill-sorted fqs even without `--pruneunsorted`, right?

**Comment by ranjitjhala** [comment]
Yes, LH shouldn't. The fix, unfortunately is a bit of work so likely won't
happen soon...
