### ISSUE TITLE
elaborate crashes on 05-case-study-eval.lhs.fq

### ISSUE THREAD

**Issue by gridaphobe** [ucsd-progsys/liquid-fixpoint#289]
On behalf of @ranjitjhala 

elaborate crashes on:
rjhala@goto.ucsd.edu:~/public_html/05-case-study-eval.lhs.fq 

Also link to ucsd-progsys/liquidhaskell#942

**Comment by ranjitjhala** [comment]
Thanks, I can only interact with GH by mail... sigh.

**Comment by ranjitjhala** [comment]
Fixed by #291
