### ISSUE TITLE
"_|_" is parsed as 'POr'

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquid-fixpoint#298]
parsing `_|_` results in `POr []`, not the expected `EBot`

**Comment by nikivazou** [comment]
Correct, because disjunction of an empty list is false.
Dually true us encoded as a conjunction of an empty list!

**Comment by alanz** [comment]
Hmm, perhaps it is a result of

```haskell
pattern EBot          = POr  []
```

**Comment by alanz** [comment]
So maybe we should return `POr []` in the parser and do away with `EBot` completely?

**Comment by ranjitjhala** [comment]
Why do we have this at all? why not just `False` ?

**Comment by alanz** [comment]
FWIW, `_|_` does not appear in the test suites of either `liquidhaskell` or `liquid-fixpoint`.

**Comment by nikivazou** [comment]
Well, all these `_|_`, `False` and `POr []` are semantically equivalent and all represented as `POr []` internally. 

I have never writen `_|_` myself, should be there for historical reason (that are described in the original Liquid Types paper). 

Ranjit, there is no `False` data constructor.

**Comment by gridaphobe** [comment]
Looks like @nikivazou replaced the `PFalse` and `PTrue` constructors with the PatternSynonyms in 8eed3ca982a33bb4cafabbee95e23e9e04088958. I vaguely recall having some discussion about it around the time of the `Expr`/`Pred` merge, seems reasonable to me..

**Comment by ranjitjhala** [comment]
What seems reasonable? Removing support for this?

**Comment by nikivazou** [comment]
Defining `False` as `POr []` is reasonable
