### ISSUE TITLE
Test suite failure in liquid-fixpoint-0.7.0.1

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquid-fixpoint#321]
Previous versions used to work fine, but after updating to `liquid-fixpoint-0.7.0.1` we now get [test suite failures in NixOS](https://github.com/ucsd-progsys/liquidhaskell/issues/1038) that look pretty much exactly like those I reported several months ago in https://github.com/ucsd-progsys/liquidhaskell/issues/1038:

~~~
      NonLinear.fq:           OK (0.06s)
      poly1.fq:               OK (0.06s)
      poly0.fq:               OK (0.06s)
      hex00.fq:               OK (0.05s)
      test3.fq:               OK (0.05s)
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
test: readCreateProcess: git "show" "--format=\"%d\"" "--quiet" (exit 128): failed
Test suite test: FAIL
~~~

This feels really odd and I wonder why I spend my spare time debugging that stuff. Do you guys care about other people being able to run those tests? Should we maybe just disable all your test suites in our builds?

**Comment by ranjitjhala** [comment]
Oops! Sorry about this! This looks like a consequence of adding circle
integration to fixpoint...(and not updating the test scripts suitably).

I will fix this (same issue as the earlier LH one) but yes, it's probably
best to disable the test suites for your builds.


Yes it's probably

**Comment by ranjitjhala** [comment]
Hi @peti,

My apologies again! This is fixed in

 https://hackage.haskell.org/package/liquid-fixpoint-0.7.0.2

(running `make` on the tarball seems to do the right thing.)

However, probably best to disable tests because as in the LH 
one, it often depends on other libraries/dependencies which 
"work out of the box" with `stack` but which I'm not sure how
to incorporate when running with just `cabal test`.

**Comment by peti** [comment]
Why don't you run the test suite with cabal test on travis-ci to ensure that they work?

**Comment by gridaphobe** [comment]
We do run it on travis, but travis also has the git repository, so the error won't appear.

I guess we could have travis build a release tarball and then build/test from that.

**Comment by peti** [comment]
The travis-ci generator from https://github.com/hvr/multi-ghc-travis does that automatically, btw. It runs the test suite from an sdist-generated tarball. This is a good idea in general to detect missing files etc.

**Comment by gridaphobe** [comment]
Huh, I wasn't aware of that. Last I checked it only built the project, it didn't run the test suite.

Regardless, we should definitely do this, thanks for the reports!
