### ISSUE TITLE
Parse ADTs in plaintext fq

### ISSUE THREAD

**Issue by atondwal** [ucsd-progsys/liquid-fixpoint#327]
Currently the ADTs seem to only work with the `bfq` files. The `fq` pretty printer prints them, but we can't parse them. eg:

```haskell
{-@ LIQUID "--higherorder" @-}
import Prelude hiding ( Maybe (..) )

data Maybe a = Just a | Nothing
```
produces 
```
± liquid asdf.hs --save
LiquidHaskell Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************


**** DONE:  Extracted Core using GHC *******************************************


**** DONE:  Transformed Core ***************************************************

Saving Binary Query: /home/atondwal/src/liquidhaskell/.liquid/asdf.hs.bfq

Saving Text Query: /home/atondwal/src/liquidhaskell/.liquid/asdf.hs.fq


**** DONE:  Uniqify & Rename ***************************************************

Working 100% [=================================================================]
Saving Solution: /home/atondwal/src/liquidhaskell/.liquid/asdf.hs.fqout


**** DONE:  annotate ***********************************************************


**** RESULT: SAFE **************************************************************
atondwal@hertz|~/src/liquidhaskell on develop?
± fixpoint .liquid/asdf.hs.fq


Liquid-Fixpoint Copyright 2013-15 Regents of the University of California.
All Rights Reserved.

Oops, unexpected error: .liquid/asdf.hs.fq:4:1-4:1: Error
  doParse has leftover
      []


syms 0
fuel [16 : 2;
      1 : 2;
      17 : 2;
      2 : 2;
      18 : 2;
[...]
```

**Comment by ranjitjhala** [comment]
Yes, the whole .fq file thing is super broken.

the issue is not parsing the datatypes but that
`syms 0` and `fuel` etc.

Btw, @nikivazou -- why do we still have that fuel stuff?

Can we delete it please?


On Thu, Sep 14, 2017 at 10:50 AM, Anish Tondwalkar <notifications@github.com

**Comment by atondwal** [comment]
> the issue is not parsing the datatypes but that `syms 0` and `fuel` etc.

Hmm, I thought I'd fixed that before the POPL deadline.

> why do we still have that fuel stuff?

IIRC we still have two tests that use it. I can get rid of it.

**Comment by ranjitjhala** [comment]
Please submit the .fq file that causes the problem (add it to `liquid-fixpoint/tests/todo/T327.fq`)

**Comment by atondwal** [comment]
Ah, so this is a "parser bug" in the sense that the parser isn't inverse to the printer, but there's an established format for the `data` decls that is informally specified in the LF tests in fqs (whereas there are no printer tests), so we should consider the REAL bug that the printer doesn't print the right thing.
