### ISSUE TITLE
instantiate: incompatible sorts

### ISSUE THREAD

**Issue by atondwal** [ucsd-progsys/liquid-fixpoint#332]
Moving ucsd-progsys/liquidhaskell#1090 here. The gist of the issue is that when we instantiate, we "uncover" calls that need functions that haven't been monomorphized at that, so we need to monomophize "as we go".

See `tests/todo/1090.fq` and `[TODO]: dynamic-apply-declaration`

**Comment by ranjitjhala** [comment]
Great can you confirm that this test fails when invoked directly with
fixpoint?

**Comment by atondwal** [comment]
I can

**Comment by atondwal** [comment]
Wow, this is strange! This test hits that bug with `Z3 version 4.5.0 - 64 bit`, `Z3 version 4.4.2`, but *not* `Z3 version 4.4.1` --- so triggers the bug on my machine, on goto, but *not* on circle!

**Comment by atondwal** [comment]
I wonder if this is a fluke, or if I should file a bug/regression with `z3`?

**Comment by ranjitjhala** [comment]
The Z3 folks know about this issue already, see:

https://github.com/Z3Prover/z3/issues/1186#issuecomment-319448921

Nikolaj says the annotation mechanism is ad-hoc
(i.e. presumably changes across versions) and
that one should not rely upon it.

So instead annotate all the uses of polymorphic
data constructors.
