### ISSUE TITLE
liquid-fixpoint-0.7.0.3 build fails during Haddock phase

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquid-fixpoint#339]
This happens with GHC 8.0.2:

~~~
src/Language/Fixpoint/Solver/Instantiate.hs:277:7: error:
    parse error on input ‘-- | (EVar dc', es) <- splitEApp e
      -- , dc == dc', length xs == length es
      -- = addSMTEquality γ (EApp (EVar f) e) (subst (mkSubst $ zip xs es) bd)
      -- >> return e
~~~

**Comment by ranjitjhala** [comment]
@nikivazou apologies for introducing the above! -- can you resubmit to hackage please? I guess we really should do a `stack haddock` before pushing to hackage...  my bad!

**Comment by ranjitjhala** [comment]
@nikivazou I have also bumped the LF and LH versions and edited the .cabal files (did I do it right?)

**Comment by ranjitjhala** [comment]
I think I've fixed the issue, and pushed a new version of LF to Hackage. 

[I cannot seem to push LH though; getting some strange error:

```
rjhala@borscht ~/r/s/liquidhaskell (develop)> cabal upload dist/liquidhaskell-0.8.0.5.tar.gz
Hackage username: ranjitjhala
Hackage password:
Uploading dist/liquidhaskell-0.8.0.5.tar.gz...
Error: dist/liquidhaskell-0.8.0.5.tar.gz: 400 Bad Request
Error: Invalid package

'hs-source-dirs: devel' directory does not exist.
```

@gridaphobe or @nikivazou any idea what the above is?

**Comment by gridaphobe** [comment]
@ranjitjhala I would recommend adding a `stack haddock` to the circle script, probably after this line

https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/circle.yml#L38

(and similarly for LH). It's irritating how haskell comments and guards combine to cause these issues, but c'est la vie..

For the hackage upload issue, we probably need to add `devel/Paths_liquidhaskell.hs` to the `extra-sour ce-files` stanza, as cabal is either not able to figure out that it needs to include the file, or hackage has become smarter at rejecting bad packages..

**Comment by ranjitjhala** [comment]
Hi @gridaphobe thanks that makes sense! But Paths_liquidhaskell was auto
generated right? Why should it need to be part of the cabal package?

**Comment by gridaphobe** [comment]
I added the `devel/Paths_liquidhaskell.hs` (and the associated `include`
flag) a long time ago to make it easier to develop LH. It overrides the
autogenerated file to tell LH to look in the current directory for the
.spec files, so you don't need to `stack build` each time you make an
edit to them. It needs to be part of the cabal package in order for it
to override the autogenerated Paths module, we just default the flag to
False so it doesn't affect user installs.

**Comment by ranjitjhala** [comment]
Just pushed a new version to hackage that hopefully fixes this.

**Comment by peti** [comment]
liquid-fixpoint-0.7.0.5 compiles fine. Thank you very much!
