### ISSUE TITLE
Hackage release 8.0.2 needs stronger bounds

### ISSUE THREAD

**Issue by BillHallahan** [ucsd-progsys/liquid-fixpoint#409]
The version of this package on Hackage:
[http://hackage.haskell.org/package/liquid-fixpoint-0.8.0.2](http://hackage.haskell.org/package/liquid-fixpoint-0.8.0.2)
says that it requires base be in the range `>=4.9.1.0 && <5`.  However, version 8.0.2 relies on Semigroup being part of base, so the dependency should actually be `>=4.11.0.0 && <5` (notice the different lower bound).

This can be fixed by a maintainer without having to upload a new release, using the "edit package information" link on the Hackage page.

**Comment by nikivazou** [comment]
Should be fixed now! Thanks!

**Comment by BillHallahan** [comment]
Thanks!
