### ISSUE TITLE
liquid-fixpoint-0.2.1.1 build failure

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquid-fixpoint#44]
Citing from http://hydra.cryp.to/build/536618/nixlog/1/raw:

    Linking dist/build/fixpoint/fixpoint ...
    /bin/sh: ./configure: /bin/bash: bad interpreter: No such file or directory
    EXEC: ./configure
    Setup: cmd: ./configure failure code 126

I believe the most portable way to refer to `bash` is to start it as `/usr/bin/env bash`. `/bin/bash` does not exist on many system, i.e. most BSD Unices don't have that. Neither does NixOS, which is what I'm running.

**Comment by ranjitjhala** [comment]
Whoops! Thanks for pointing this out! We'll update the build script shortly!

**Comment by gridaphobe** [comment]
@peti this should be fixed in the new `liquid-fixpoint-0.2.2.0` release.

**Comment by peti** [comment]
Unfortunately, the 0.2.2.0 build fails exactly the same way: http://hydra.cryp.to/build/537199/log/raw.

**Comment by peti** [comment]
Duh, wait! I just realized that the new build has a different error. It fails because it can't find `/usr/bin/env`! :flushed:

Now I'm a little worried, because I would have bet that this path is available inside of a Nix chroot environment, but apparently it isn't???

**Comment by peti** [comment]
I suppose this issue needs to be fixed in NixOS: https://github.com/NixOS/nixpkgs/issues/6227. Thank you for your efforts!
