### ISSUE TITLE
--eliminate=existentials acts weirdly

### ISSUE THREAD

**Issue by serras** [ucsd-progsys/liquid-fixpoint#450]
I've found this weird case. The following is considered safe:

```
(fixpoint "--eliminate=existentials")

(var $k ((Int)))

(constraint
  (and
    (forall ((x int) ($k x)) ((x == 0)))
    (exists ((x int) (true)) (($k x)))
  )
)
```

but if I change `x == 0` to `x >= 0`, then I get unsafe as result.

**Comment by ranjitjhala** [comment]
The “exists” variables are super new and a bit brittle - they are sensitive
to equalities.

I’d strongly suggest not using it and sticking to the plain “for all”
constraints.
