### ISSUE TITLE
Multiple BitVector bindings

### ISSUE THREAD

**Issue by panagosg7** [ucsd-progsys/liquid-fixpoint#48]
See
https://github.com/panagosg7/liquid-fixpoint/blob/master/tests/bitvector-buggy.fq

The extra BitVector binding causes crash.

**Comment by ranjitjhala** [comment]
Odd! I'll look into this this morning

**Comment by ranjitjhala** [comment]
Oops. I *still* can't write regexps! 

Fixed by https://github.com/ucsd-progsys/liquid-fixpoint/commit/57f35df8ce5c837ac1ee284e49788ce9870ae0cf
