### ISSUE TITLE
Serialize formulas only once

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquid-fixpoint#494]
Currently, when we try to validate a constraint, we send to the SMT solver all the formulas in the environment and the right-hand-side of the constraint.

The problem is that many bindings in the environments of constraints are shared. So whenever multiple constraints are validated, all the shared bindings are serialized over and over, and serialization is relatively expensive. This is an important bottleneck in StitchLH.

I see two ways to reduce the duplicated effort. 

### 1. Cache the result of serializing a binding.

In this approach, we store together with each binding, the result of serializing it. Thus, whenever we need to validate a constraint that uses a binding, we send the cached bytestring to the SMT solver.

### 2. Load the bindings into the smt solver without asserting them.

How about we define a function for each binding?
```
define-fun f1 () Bool (long formula of binding 1)
define-fun f2 () Bool (long formula of binding 2)
```
Then when we need to validate a constraint we just say
```
assert (f1 && f2)
```
Instead of 
```
assert (long formula of binding 1 && long formula of binding 2)
```
I'm not very familiar with SMTLIB2, so maybe there is a better way to achieve the same effect.

I feel like trying (2) for a start. Any thoughts?

**Comment by ranjitjhala** [comment]
Hi @facundominguez  -- I have *long* wanted to try something like (2), I think its an excellent thing to try. I was somehow under the impression that we were _already_ doing (1) but maybe that's just wishful thinking on my part -- I agree, given how much time is spent in serialize* this would be great to try! 

* I need to double check but I seem to recall a _significant_ chunk of time in `fixpoint` is spent in serialize; do you also have some profile data to that effect?

**Comment by facundominguez** [comment]
Here's a flamegraph for verifying [Step.hs.bfq](https://github.com/facundominguez/stitch-lh/blob/main/src/Language/Stitch/LH/Step.hs) from StitchLH. It currently takes near 20 seconds to verify. 
[fixpoint.svg.zip](https://github.com/ucsd-progsys/liquid-fixpoint/files/7268992/fixpoint.svg.zip)

The serialization time reaches to a bit over 40% of the total.

**Comment by ranjitjhala** [comment]
Btw, does the `Step.hs` file use `reflection` and `ple`?

**Comment by facundominguez** [comment]
I edited the previous message to include the link to the file. Yes, it does use ple and some of the imported functions are reflected.

**Comment by ranjitjhala** [comment]
Super @michaelborkowski when you get a chance can you check if your interpreter-ple does better on this benchmark?

**Comment by facundominguez** [comment]
The description of #495 says:

> Two further improvements to do in subsequent PRs would be:
>
> * Have PLE use the serialized bindings. Right now it ignores them.
> * Have PLE not modify existing bindings as a result, but instead add new bindings with the new equations.

I'm going to defer on these until I find a benchmark where fixing those makes a bigger difference. In the Step.hs module we can't shave more than 3% or 4%.
