### ISSUE TITLE
`nix-build` and `nix-shell` error: "called without required argument"

### ISSUE THREAD

**Issue by curiousleo** [ucsd-progsys/liquid-fixpoint#506]
Hi, the Nix setup isn't working for me on b02601f49f01578bd5158a5d29bf0e1c685b7f89.

```console
$ uname -a
Linux phoebe 5.10.76 #1-NixOS SMP Wed Oct 27 07:56:57 UTC 2021 x86_64 GNU/Linux
```

```console
$ nix-shell
error: anonymous function at /nix/store/nj5pzc098vcxifbla0nd9wxpyg03vlj8-cabal2nix-liquid-fixpoint/default.nix:1:1 called without required argument 'rest-rewrite', at /nix/store/2gvpjwk27dng6c6vw3q3dpfdbza91wmn-source/pkgs/development/haskell-modules/make-package-set.nix:87:27

$ nix-build .
error: anonymous function at /nix/store/nj5pzc098vcxifbla0nd9wxpyg03vlj8-cabal2nix-liquid-fixpoint/default.nix:1:1 called without required argument 'rest-rewrite', at /nix/store/2gvpjwk27dng6c6vw3q3dpfdbza91wmn-source/pkgs/development/haskell-modules/make-package-set.nix:87:27

$ nix-build . -A haskellPackages.liquid-fixpoint
error: anonymous function at /nix/store/nj5pzc098vcxifbla0nd9wxpyg03vlj8-cabal2nix-liquid-fixpoint/default.nix:1:1 called without required argument 'rest-rewrite', at /nix/store/2gvpjwk27dng6c6vw3q3dpfdbza91wmn-source/pkgs/development/haskell-modules/make-package-set.nix:87:27
```

**Comment by curiousleo** [comment]
The nixpkgs pin is quite old. I would be happy to give updating the Nix setup a shot, perhaps with the help of https://github.com/nmattia/niv, if there is interest in getting the Nix setup to work.

**Comment by facundominguez** [comment]
Hello Leo! I've been building liquid-fixpoint with the setup in https://github.com/ucsd-progsys/liquidhaskell which is based on `stack`. It looks to me like a copying that setup here would be simplest to maintain since it requires the less nix-specific configuration. But if there are other nix users here, they can weigh in.

**Comment by curiousleo** [comment]
> It looks to me like a copying that setup here would be simplest to maintain since it requires the less nix-specific configuration.

That sounds like a great idea to me.
