### ISSUE TITLE
How bad is this message?

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquid-fixpoint#52]
https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/ast.ml#L1192

ie., can I safely ignore it?

@ranjitjhala

**Comment by ranjitjhala** [comment]
Probably shouldn't happen but can be deferred to after the deadline...?

**Comment by nikivazou** [comment]
I think we can defer/ignore it, but I wanted you to verify it:)

This is the minimal LiquidHaskell example:

~~~
data F a = F a
{-@ F :: x:a -> {v:F a | v = F x} @-}
~~~

that triggers

~~~
========================================================
© Copyright 2009 Regents of the University of California.
All Rights Reserved.
========================================================
sortcheck_app_sub: unknown sym = Fixme.F#rpv
.|
SAT
~~~

**Comment by ranjitjhala** [comment]
This is bad: it should be rejected as a malformed spec unless we lift "F" into the logic...

Eg can you try this code:

foo :: x:a -> y:a -> {v = F x}
foo x y = F y

I fear it will pass.

**Comment by ranjitjhala** [comment]
Which is clearly unsound.

**Comment by nikivazou** [comment]
~~~
{-@ foo :: x:a -> y:a -> {v:F a | v = F x} @-}
foo x y = F y 
~~~
soundly fails with 

~~~
 tests/pos/fixme.hs:9:11-13: Error: Liquid Type Mismatch
   Inferred type
     VV : (F a) | VV == Fixme.F y

   not a subtype of Required type
     VV : (F a) | VV == Fixme.F x

   In Context
     VV : (F a) | VV == Fixme.F y
     y  : a
     x  : a
~~~

**Comment by nikivazou** [comment]
Interestingly, there is no
~~~
sortcheck_app_sub: unknown sym = Fixme.F#rpv
~~~
in 
~~~
{-@ foo :: x:a -> y:a -> {v:F a | v = F y} @-}
foo x y = F y 
~~~

I suspect `F` gets into scope when it appears in the code (and not only in the specifications)
as mentioned in  ucsd-progsys/liquidhaskell#337

**Comment by ranjitjhala** [comment]
Hmm ok... But you can have malformed data definitions so we should fix this ASAP after icfp

**Comment by gridaphobe** [comment]
@nikivazou yes this sounds familiar. Datacons are definitely lifted into the logic (and have been for quite some time) when they appear in the CoreBinds. IIRC this is perhaps the sole purpose of the `freeSymbols` stuff in Bare.

**Comment by nikivazou** [comment]
Correct, this is unsoundly SAFE

~~~
data F a = F a a
{-@ F :: x:a -> y:a ->  {v:F a | v = F y x} @-}
~~~



@gridaphobe, Datasons should be lifted even if they do not appear in CoreBinds, IMO

**Comment by gridaphobe** [comment]
I totally agree :)

**Comment by spinda** [comment]
I think the two issues may be unrelated. This fails:

```haskell
data F a = F a a

{-@ foo :: x:a -> y:a -> {v:F a | v = F y x} @-}
foo :: a -> a -> F a
foo x y = F x y
```

```
 tests/todo/hmm.hs:5:11-15: Error: Liquid Type Mismatch
   Inferred type
     VV : (F a)
  
   not a subtype of Required type
     VV : (F a) | VV == Main.F y x
  
   In Context
     VV : (F a)
     x  : a
     y  : a
```

whereas this passes:


```haskell
data F a = F a a
{-@ F :: x:a -> y:a ->  {v:F a | v = F y x} @-}

{-@ foo :: x:a -> y:a -> {v:F a | v = F y x} @-}
foo :: a -> a -> F a
foo x y = F x y
```

It's as if standalone signatures on datacons are assumed, not checked.

**Comment by gridaphobe** [comment]
@nikivazou is this still an issue? The line you linked to has changed, so I'm not sure what the original issue was :)

**Comment by nikivazou** [comment]
The issue is warnings like 

```
sortcheck_app_sub: unknown sym = Fixme.F#rpv
```

I still get them, but ignore them.

**Comment by gridaphobe** [comment]
Is it something that can/should be fixed before I make another release? (ie in the next few days?)

**Comment by nikivazou** [comment]
I guess if these warnings are not important we can suppress them.

**Comment by ranjitjhala** [comment]
Folks, what is the status of this?

**Comment by nikivazou** [comment]
I haven't seen these warnings for a while. Let's close it for now.
