### ISSUE TITLE
Add upper bound <0.2 for rest-rewrite

### ISSUE THREAD

**Issue by andrewthad** [ucsd-progsys/liquid-fixpoint#526]
Also, add this bound as a hackage revision. `rest-rewrite-0.2` changes the names of modules and `liquid-fixpoint` is not compatible with it.

**Comment by philderbeast** [comment]
We're on a later version now. Can this issue be closed?

https://github.com/ucsd-progsys/liquid-fixpoint/blob/48b997ac1a0b2a7b6d1521beaece6a40cfcf0c5f/liquid-fixpoint.cabal#L148
