### ISSUE TITLE
'ple_sum_fuel.5.smt2' tests fail after 'rest-rewrite' bump

### ISSUE THREAD

**Issue by waivio** [ucsd-progsys/liquid-fixpoint#536]
I ran into some problems, I worked with @facundominguez, to bump the
`rest-rewrite` library to use a more modern version of `hashable`.
During this effort @facundominguez recomended that I attempt to fix
the upstream dependencies of the library.  The only library dependent on
`rest-rewrite` is `liquid-fixpoint`, and that is convenient because I
would also like to do some ground-work to get it working with
`ghc-9.0.2`.  When I made the simple change to bump the `hashable`
version to `hashable-1.3.5.0` and update the `rest-rewrite` commit to
the final version, the `liquid-fixpoint` tests failed in two spots:

```
      ple_sum_fuel.5.smt2:    FAIL (0.04s)
        tests/test.hs:118:
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
        Use -p '/horn-neg-el.ple_sum_fuel.5.smt2/' to rerun this test only.
```
and
```
      ple_sum_fuel.5.smt2:    FAIL (0.04s)
        tests/test.hs:118:
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
        Use -p '/horn-neg-na.ple_sum_fuel.5.smt2/' to rerun this test only.

```

Apparently the test is expecting failure:
```
    , testGroup "horn-pos-el" <$> dirTests elimCmd   "tests/horn/pos"  []          ExitSuccess
    , testGroup "horn-neg-el" <$> dirTests elimCmd   "tests/horn/neg"  []          (ExitFailure 1)
    , testGroup "horn-pos-na" <$> dirTests nativeCmd "tests/horn/pos"  []          ExitSuccess
    , testGroup "horn-neg-na" <$> dirTests nativeCmd "tests/horn/neg"  []          (ExitFailure 1)
```
And now it is passing instead of `(ExitFailure 1)`.

Apparently the two tests are the same, but with different values of the
`--fuel` value.

```
(constant sum  (func(0, [int, int])))

(define sum(n : int) : int = { if (n <= 0) then (0) else (n + sum (n-1)) })

(constraint 
   (forall ((x int) ((5 <= x) && (0 <= (sum (x-5))))) 
       ((15 <= (sum x)))
   )
)
```

I am having trouble understanding this case, because if I plug in either
`5` or `6` into the constraint, both would yield true.

So I don't know what is going on here.  The change to `rest-rewrite`
and `hashable` seemed pretty innocuous.

**Comment by ConnorBaker** [comment]
For what it's worth, I saw the same behavior: https://github.com/ConnorBaker/liquid-fixpoint/commit/51e4bbc87c73ff9e403bd75f75e0d245bad55ad3.

Dropping the fuel unit down by one fixed both.

**Comment by ranjitjhala** [comment]
This is strange … @niki or @mborkowski any idea?

**Comment by ConnorBaker** [comment]
Is it possible that this was caused by using a different version of SMT solver?

Is there any sort of regression test run with new releases of SMT solvers, or documentation of which versions work well?

**Comment by facundominguez** [comment]
I found when working on #500 that this test allows more unfoldings than necessary. I fixed it in the yet unmerged 7170cedf7. However, I only came across this problem after modifying PLE with some optimization attempts.

If you'd like to get this unblocked, maybe we could just reduce the fuel of the test, and revisit it when merging the above patch. PLE is easier to inspect with the work of #500 rather than in the current form.

**Comment by waivio** [comment]
How can we improve the documentation about the test?

- What is PLE?
- Why should this test fail?
- What is this failure trying to prove?
- What is fuel in this context?
- What is positive and negative in this context?
- What is el and na in this context?

Maybe the test should be changed to pass...??
I don't know.

**Comment by facundominguez** [comment]
> What is PLE?

I think an overview is missing in the description of liquid-fixpoint to list the major algorithms and their publications. This one is for PLE (proof by logical evaluation): https://ranjitjhala.github.io/static/refinement_reflection.pdf

> Why should this test fail?

Because it is supposed to be limited how many times liquid-fixpoint is going to unfold definitions to discover the equality.

> What is this failure trying to prove?

That the limit on the amount of unfoldings is respected.

> What is fuel in this context?

The maximum amount of unfoldings permitted per reflected function.

> What is positive and negative in this context?

Positive: Modules whose verification is expected to pass.
Negative: Modules whose verification is expected to fail.

> What is el and na in this context?

This one I don't know.

**Comment by waivio** [comment]
Thanks @facundominguez for the much needed explanation. After looking at the code more, I think the 'el' is for 'elemCmd' TestCmd, and 'na' is for the 'nativeCmd' TestCmd.

I attached snippets of the resulting change in unfolding/in-lining if anyone is interested to view the diff:
[after_version_bump.txt](https://github.com/ucsd-progsys/liquid-fixpoint/files/8454389/after_version_bump.txt)
[before_version_bump.txt](https://github.com/ucsd-progsys/liquid-fixpoint/files/8454390/before_version_bump.txt)

It does look like the 'rest-rewrite' bump would require less fuel for the solver to find a solution.

I made code changes similar to the @ConnorBaker commit, and will try and PR them shortly.

**Comment by waivio** [comment]
All Merged. Thanks Everyone!

**Comment by ranjitjhala** [comment]
Thank you!!!

**Comment by ranjitjhala** [comment]
I think that’s a good idea - (reduce fuel and revisit?)
