### ISSUE TITLE
Polymorphic instantiation

### ISSUE THREAD

**Issue by panagosg7** [ucsd-progsys/liquid-fixpoint#56]
The following seems to cause a "Bad Constraint", as the return type of `offset` does not get instantiated correctly.
```
constant offset : func(1, [int; @(1)])

constraint:
  env []
  grd true
  lhs {v : int | [v = 1; (offset([1]) = 0)]}
  rhs {v : int | [v = 1 ]}
  id 1 
```
The following make the error go away:
* Defining `offset` as `constant offset : func(0, [int; int])`
* Using `offset([1]) ~~ 0` & the `-u` flag, instead of `offset([1]) = 0`

**Comment by ranjitjhala** [comment]
This is strange. Can you see if

  0 = offset([1])


works?



On Mon, Mar 16, 2015 at 2:59 PM, Panagiotis Vekris <notifications@github.com
> wrote:

> The following seems to cause a "Bad Constraint", as the return type of
> offset does not get instantiated correctly.
>
> constant offset : func(1, [int; @(1)])
>
> constraint:
>   env []
>   grd true
>   lhs {v : int | [v = 1; (offset([1]) = 0)]}
>   rhs {v : int | [v = 1 ]}
>   id 1
>
> The following make the error go away:
>
>    - Defining offset as constant offset : func(0, [int; int])
>    - Using offset([1]) ~~ 0 instead of offset([1]) = 0
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/56>.
>



-- 
Ranjit.

**Comment by panagosg7** [comment]
That also fails

**Comment by ranjitjhala** [comment]
Blugh pretty sure there is a fixpoint option that needs to be triggered; as I had to fix this elsewhere...

Let me take a look...

**Comment by ranjitjhala** [comment]
Can you add a dummy binder 

z : v=0 

To the env and replace 

= 0

With 

= z

And check if that works?

**Comment by panagosg7** [comment]
Yup, that seems to fix it.

**Comment by ranjitjhala** [comment]
okay, I will extend that patch took account for this case as well

**Comment by ranjitjhala** [comment]
Just updated liquid-fixpoint can you see if the new thing works for you?

On Mon, Mar 16, 2015 at 4:20 PM, Ranjit Jhala <rjhala@eng.ucsd.edu> wrote:

> okay, I will extend that patch took account for this case as well
>
> On Mar 16, 2015, at 4:08 PM, Panagiotis Vekris <notifications@github.com>
> wrote:
>
> Yup, that seems to fix it.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/56#issuecomment-81981948>
> .
>
>


-- 
Ranjit.

**Comment by panagosg7** [comment]
Yes, this seems to fix this. Thanks!
