### ISSUE TITLE
Crash on Untyped Qualifiers

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquid-fixpoint#59]
The following [code](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tests/UnTypedQuals.fq)

~~~
qualif Auto1(VV : FAppTy SumFst.L  a_apx): ((? barr([VV])) <=> true) // "tests/pos/fixme.hs" (line 3, column 12)
qualif Auto2(VV : FAppTy SumFst.L  a_apx): (bar([VV]) = 0) // "tests/pos/fixme.hs" (line 3, column 12)

constant bar : func(0, [FAppTy SumFst.L  int; int])
constant barr : func(0, [FAppTy SumFst.L  int; bool])
~~~

Crashes with 

~~~
No type for barr([VV])z3Pred: error converting (barr(VV) <=> true)
Fatal error: exception Assert_failure("tpGen.ml", 355, 24)
~~~

I.e. the `Auto1` qualifier is untyped. But these is no such issue for the `Auto2` qualifiers. 
So, @ranjitjhala do we allow unsorted qualifiers or not?

The above error is created from the following liquidHaskell code

~~~
data L a = Nil

{-@ measure bar :: L Int -> Int
    bar Nil = 0
  @-}	

{-@ measure barr :: L Int -> Prop
    barr Nil = true
  @-}	  
~~~

Where the qualifiers are stripped from the type of Nil

~~~
Nil :: {v:L a | bar v == 0 && barr v <=> true} 
~~~

**Comment by nikivazou** [comment]
The crash is created by the line 

https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tpGen.ml#L206

What is the purpose of this line? May I remove it?

**Comment by nikivazou** [comment]
So, removing the above line makes other liquidHaskell tests crash. 
For example, `tests/pos/elements.hs` crashes with 
~~~
Fatal error: exception Failure("z3AppThy: sort error Set_empty([0])")
~~~

and `tests/pos/ListElems.hs` is UNSAFE.

**Comment by ranjitjhala** [comment]
@nikivazou what is the exact command to fixpoint.native that triggers the above collapse?

**Comment by nikivazou** [comment]
I just run fixpoint.native no parameters or liquid on the haskell file

**Comment by ranjitjhala** [comment]
OK, so the "problem" is that the qualifier 

```
qualif Auto2(VV : FAppTy SumFst.L  a_apx): (bar([VV]) = 0) // "tests/pos/fixme.hs" (line 3, column 12)
```

is "malformed" because the `bar(VV)` is not well typed (as `bar :: Int -> Int` but is applied here to `VV::a`.

You can fix it by **EITHER** changing the above qualifier to:

```
qualif Auto2(VV : FAppTy SumFst.L  int): (bar([VV]) = 0) // "tests/pos/fixme.hs" (line 3, column 12)
```

**OR** by making `bar` polymorphic:

```
constant bar : func(1, [FAppTy SumFst.L  @(0); int])
```

I say "problem" because this is somewhat a consequence of my hacky 
implementation of sort- polymorphism in fixpoint. (At any rate this should
be flagged as a nicer error instead of the gross thing we have now, I'm surprised
we've never seen it  before!)

**Comment by nikivazou** [comment]
Ok, sorry the exact command is the one that liquid uses:

~~~
fixpoint.native -v 1  -notruekvars -refinesort -nosimple -strictsortcheck -sortedquals -no-gen-qual-sorts -smtsolver z3 tests/UnTypedQuals.fq
~~~

The problem is a bit more hacky:
`fixpoint` likes the qualifier `Auto2` even though it is malformed. But rejects (and crashes on) `Auto1` which is equally malformed. If you delete the first line in my initial example there is no crash.

Given that  `((? barr([VV])) <=> true)` is a `Pred` and `(bar([VV]) = 0)` is an `Expr`,
the first one is checked via `z3Pred` 
https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tpGen.ml#L333
and is rejected, while the second is checked via `z3Expr` https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/tpGen.ml#L298 and is accepted.

**Comment by ranjitjhala** [comment]
@nikivazou did you see my comment above? **BOTH** qualifiers are "bad" and i get errors if I leave either one in the file...

**Comment by nikivazou** [comment]
What do you mean "you get errors"? 

If I run `fixpoint.native` on 
~~~
qualif Auto2(VV : FAppTy SumFst.L  a_apx): (bar([VV]) = 0) // "tests/pos/fixme.hs" (line 3, column 12)

constant bar : func(0, [FAppTy SumFst.L  int; int])
~~~

I get `SAT` and no error!

**Comment by nikivazou** [comment]
Btw, I agree that both qualifiers are BAD, but 
1. `Auto2` is incorrectly not treated as bad, and
2. Apparently, liquidHaskell relies on this "feature" to implement "malformed" measures, ie the measures that for example apply to `List Int` instead of `List a`.

**Comment by ranjitjhala** [comment]
hmm... not sure what you mean by "1" or "2" lets discuss in person tomorrow?

On Tue, Apr 21, 2015 at 2:14 PM, Niki Vazou <notifications@github.com>
wrote:

> Btw, I agree that both qualifiers are BAD, but
> 1. Auto2 is incorrectly not treated as bad, and
> 2. Apparently, liquidHaskell relies on this "feature" to implement
> "malformed" measures, ie the measures that for example apply to List Int
> instead of List a.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/59#issuecomment-94945178>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
ok!

**Comment by ranjitjhala** [comment]
ah, ok -- i was getting them BOTH to fail because I had uncommented an
extra ASSERT in the code :-/  -- now I can replicate the problem you have.
The issue is you want BOTH to be rejected right? (independently)

On Tue, Apr 21, 2015 at 2:18 PM, Niki Vazou <notifications@github.com>
wrote:

> ok!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/59#issuecomment-94945986>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
Nice!

The issue is that I can see why both should fail, but liquidHaskell depends on them not failing (see "2" above).

So if we fix liquid-fixpoint so that they both fail, we will break liquidHaskell.....

At least, both (`Auto1` and `Auto2`) should  be treated in the same way (either both fail or none.)

**Comment by ranjitjhala** [comment]
Can you explain "2" ? How does LH exactly use this feature? (Whats a
concrete example?)

On Tue, Apr 21, 2015 at 2:35 PM, Niki Vazou <notifications@github.com>
wrote:

> Nice!
>
> The issue is that I can see why both should fail, but liquidHaskell
> depends on them not failing (see "2" above).
>
> So if we fix liquid-fixpoint so that they both fail, we will break
> liquidHaskell.....
>
> At least, both (Auto1 and Auto2) should be treated in the same way
> (either both fail or none.)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/59#issuecomment-94949218>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
Consider the code
~~~
data L a = Nil

{-@ measure bar :: L Int -> Int
    bar Nil = 0
  @-}   

{-@ measure barr :: L Int -> Prop
    barr Nil = true
  @-}  
~~~

Then the type of `Nil` is

~~~
Nil :: {v:L a | bar v == 0 && barr v <=> true} 
~~~

which creates the above two qualifiers

**Comment by ranjitjhala** [comment]
but but but ... that makes no sense... i.e. the type of Nil is NOT WF...


On Tue, Apr 21, 2015 at 2:39 PM, Niki Vazou <notifications@github.com>
wrote:

> Consider the code
>
> data L a = Nil
>
> {-@ measure bar :: L Int -> Int
>     bar Nil = 0
>   @-}
>
> {-@ measure barr :: L Int -> Prop
>     barr Nil = true
>   @-}
>
> Then the type of Nil is
>
> Nil :: {v:L a | bar v == 0 && barr v <=> true}
>
> which creates the above two qualifiers
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/59#issuecomment-94950097>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
But this is how we implement these "malformed" measures.
The non-wf components are filtered out before going to fixpoint environments. 
But in Haskell environment these non wf are there.

**Comment by ranjitjhala** [comment]
Not clear if thats the most compelling argument. Maybe we need a less hacky
way to implement specialized measures :)

At any rate, for now, you can add "-allquals" to the fixpoint.native
command and it
should work fine.

On Tue, Apr 21, 2015 at 2:46 PM, Niki Vazou <notifications@github.com>
wrote:

> But this is how we implement these "malformed" measures.
> The non-wf components are filtered out before going to fixpoint
> environments.
> But in Haskell environment these non wf are there.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/59#issuecomment-94952767>
> .
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
I have a branch called "diff" on fixpoint, where I attempt to consistently
add the same
check everywhere (and you don't need that "-allquals" business.)

Can you see if it breaks any LH tests?

**Comment by ranjitjhala** [comment]
sorry can you try the "diff" branch now?

On Tue, Apr 21, 2015 at 3:46 PM, Ranjit Jhala <jhala@cs.ucsd.edu> wrote:

> I have a branch called "diff" on fixpoint, where I attempt to consistently
> add the same
> check everywhere (and you don't need that "-allquals" business.)
>
> Can you see if it breaks any LH tests?
>
>


-- 
Ranjit.

**Comment by nikivazou** [comment]
Actually, liquidHaskell does not compile with `diff` due to the extra argument in `Loc`.

**Comment by ranjitjhala** [comment]
@nikivazou why was this closed? I am getting a few failing tests on the 'cut solver' branch and I think it *may* have to do with the changes here...

**Comment by nikivazou** [comment]
I closed it because you fixed it, as it does not crash on untyped qualifiers any more.

**Comment by ranjitjhala** [comment]
well... not clear if all the regrtests are passing thanks to that "fix".


was that fix merged into master?

**Comment by nikivazou** [comment]
Yes, at least my liquidHaskell code, ie
~~~
data L a = Nil

{-@ measure bar :: L Int -> Int
    bar Nil = 0
  @-}   

{-@ measure barr :: L Int -> Prop
    barr Nil = true
  @-}  
~~~

is SAFE now on master, before it used to crash.

**Comment by nikivazou** [comment]
On liquidHaskell master  all regression tests pass.
