### ISSUE TITLE
`z3-4.10.*` versions don't work for liquid-fixpoint

### ISSUE THREAD

**Issue by philderbeast** [ucsd-progsys/liquid-fixpoint#614]
After `brew upgrade z3` I found that `cabal test all` for `liquid-fixpoint` had failures.

Incidentally I found that `pavpanchekha/setup-z3@1.2.2` can't install the latest version of z3 as ubuntu binaries are no longer being built or maybe they are under another name (a separate issue).

```yaml
      - name: Setup z3
        uses: pavpanchekha/setup-z3@1.2.2
        with:
          version: "4.8.7"
```

This `pavpanchekha/setup-z3` file name construction doesn't work for some of the newer releases.

```js
    let path = "https://github.com/Z3Prover/z3/releases/download/z3-" + version;
    let file = "z3-" + version + "-" + architecture + "-" + distribution + ".zip";
```

![Screen Shot 2022-08-02 at 7 16 50 AM](https://user-images.githubusercontent.com/633283/182362157-94bfd46e-c5e3-4831-8114-cdd4b399773e.png)

I uninstalled with `brew uninstall z3`, downloaded binaries for osx to `$HOME/dev/tools/z3/` and used [direnv](https://direnv.net/) in the `liquid-fixpoint` project root to switch z3 versions that I tested with `cabal test all`.

```
# .envrc file contents

# These z3 versions work for liquid-fixpoint's test-suite.
# PATH_add "$HOME/dev/tools/z3/z3-4.8.7-x64-osx-10.14.6/bin"
# PATH_add "$HOME/dev/tools/z3/z3-4.8.10-x64-osx-10.15.7/bin"
# PATH_add "$HOME/dev/tools/z3/z3-4.8.17-x64-osx-10.16/bin"
# PATH_add "$HOME/dev/tools/z3/z3-4.9.0-x64-osx-10.16/bin"

# The z3-4.10.* versions don't work for liquid-fixpoint.
PATH_add "$HOME/dev/tools/z3/z3-4.10.0-x64-osx-10.16/bin"
# PATH_add "$HOME/dev/tools/z3/z3-4.10.2-x64-osx-10.16/bin"
```

**Comment by philderbeast** [comment]
I've raised an issue with `setup-z3` for download file names, https://github.com/pavpanchekha/setup-z3/issues/7

**Comment by ranjitjhala** [comment]
wow thanks for catching this!

**Comment by philderbeast** [comment]
Trying the example from the readme:

```
> z3 --version
Z3 version 4.10.2 - 64 bit

> more tests/horn/pos/test01.smt2 | fixpoint --stdin


Liquid-Fixpoint Copyright 2013-21 Regents of the University of California.
All Rights Reserved.

Working  66% [============================================.....................]
Crash!: :1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 4 column 27: unknown parameter 'model_partial',
  this is an old parameter name, invoke 'z3 -p' to obtain the new parameter list"
```

```
>z3 --version
Z3 version 4.8.7 - 64 bit

> more tests/horn/pos/test01.smt2 | fixpoint --stdin


Liquid-Fixpoint Copyright 2013-21 Regents of the University of California.
All Rights Reserved.

Working 166% [=================================================================]
Safe ( 2  constraints checked)
```

Are we good with going to 166%?

**Comment by philderbeast** [comment]
The `model_partial` parameter is set like this, isn't it?

https://github.com/ucsd-progsys/liquid-fixpoint/blob/8e65556f7488f00e238d4ab61c66e7ce3b9d2b72/src/Language/Fixpoint/Smt/Interface.hs#L530-L534

I ran `z3 -p` for versions `4.8.7` and `4.10.2` and saw only additions to the model parameters with partial still there:

```diff
[module] model
    compact (bool) (default: true)
    completion (bool) (default: false)
    inline_def (bool) (default: false)
    partial (bool) (default: false)
+   user_functions (bool) (default: true)
    v1 (bool) (default: false)
    v2 (bool) (default: false)
```

**Comment by facundominguez** [comment]
Does this fix it for you?
```
- "(set-option :model-partial false)"
+ "(set-option :model.partial false)"
```

**Comment by philderbeast** [comment]
Yes `model.partial` fixes this problem.

**Comment by philderbeast** [comment]
I admit to trying `model.partial` when tired via installation but missing the `--overwrite-policy=always`.

```diff
- > cabal install exe:fixpoint
+ > cabal install exe:fixpoint --overwrite-policy=always
  > more tests/horn/pos/test01.smt2 | fixpoint --stdin
```

Not a problem when skipping the install and going with `cabal run`.

```
cabal run fixpoint -- tests/horn/pos/test01.smt2
```
