### ISSUE TITLE
Mark erroneous version as deprecated.

### ISSUE THREAD

**Issue by DrewFenwick** [ucsd-progsys/liquid-fixpoint#646]
In the latest version on Hackage, the version number jumped from `0.9.0.2.1` to `8.10.7`
I'm guessing this was supposed to be a version `0.8.10.7` or `0.8.10.7.1` 

I assume that version has already been re-published with the proper version number, but the fact that this erroneous version is still on hackage makes reading cabal build plan failure output confusing! Cabal will try to use `8.10.7` first as it's the newest version, and it took me a while to see why `8.10.7` didn't satisfy `liquid-fixpoint>=0.8.10.2.1 && <0.9`

Additionally if someone doesn't put a bound on their `liquid-fixpoint` dependency, Cabal will select `8.10.7` over `0.9.0.2.1`, which I assume would be undesirable (though I assume in most cases you'd have to pin the version to your compiler version to even get it to build).

If `8.10.7` is marked as a deprecated version on Hackage then Cabal will stop trying to use it in build plans, which solves both of these problems.

**Comment by facundominguez** [comment]
Thanks for the report!

I've have marked 8.10.7 as deprecated in hackage.

Note that trying to build from hackage will likely fail builds or tests because the packages `liquid-base`, `liquid-prelude`, etc, haven't been updated yet to match `0.9.0.2.1`. @nikivazou would you be doing these releases?

**Comment by nikivazou** [comment]
Yes, I can do it tomorrow. I tried to make you a maintainer too but I do not have the permission. @adinapoli can you please give me access to be able to add maintainers (or add @facundominguez) ?

**Comment by adinapoli** [comment]
@nikivazou You should already be maintainer at least for `liquid-base`, `liquid-prelude` and `liquid-containers`:

- https://hackage.haskell.org/package/liquid-base/maintainers/
- https://hackage.haskell.org/package/liquid-prelude/maintainers/
- https://hackage.haskell.org/package/liquid-containers/maintainers/

Are you still using that Hackage account or a different one?

**Comment by nikivazou** [comment]
I am a maintainer, but when I tried to edit the maintainers I got 

`Can't edit permissions for user group`

So, I assume being a maintainer and be able to edit the maintainers is a different set of permissions?

**Comment by adinapoli** [comment]
Sanity check: I can see you also have a `niki` account on Hackage:

https://hackage.haskell.org/user/niki

Any chance the browser's session is keeping you logged in with `niki`, preventing you from editing stuff?

I can certainly add Facundo as a maintainer of all the `liquid-*` packages, just curious on why Hackage is giving you that error 🤔

**Comment by nikivazou** [comment]
That was it :) Thanks!!! I am adding him!

**Comment by facundominguez** [comment]
> Note that trying to build from hackage will likely fail builds or tests because the packages liquid-base, liquid-prelude, etc, haven't been updated yet to match 0.9.0.2.1.

I have uploaded new releases of `liquid-*` packages by now. :)
