### ISSUE TITLE
liquid-fixpoint-0.3.0.0 fails its test suite because of missing files

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquid-fixpoint#66]
Citing from http://hydra.cryp.to/build/875820/log/raw:

~~~~~~~~~
running tests
Running 1 test suites...
Test suite test: RUNNING...
test: tests/pos: getDirectoryContents: does not exist (No such file or directory)
Test suite test: FAIL
~~~~~~~~~~

**Comment by ranjitjhala** [comment]
Oops! thats odd, will look into it, thanks for pointing out @peti

**Comment by gridaphobe** [comment]
Thanks for the report @peti, I never realized that our test files weren't included in the `tgz` :(

Just pushed a new version to hackage that should be fixed!
