### ISSUE TITLE
Function as argument

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#67]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cutsolver/tests/todo/func-arg.fq

external/fixpoint/fixpoint.native returns SAT, but the haskell solver throws an error

**Comment by ranjitjhala** [comment]
thanks for the super minimal example! will look into this asap.

**Comment by ranjitjhala** [comment]
Which is the benchmark from which this is from?

**Comment by ranjitjhala** [comment]
Pushed an edit that filters out Higher Order binders, works for this (and other tests) so closing.
