### ISSUE TITLE
Disallow bogus substitutions?

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#68]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cutsolver/tests/weird/bogus.fq

Note that this isn't just a hand-crafted edge-case - you can find a similar bogus substitution if you run liquid on https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/TopLevel.hs and then search for tmp_x_185

**Comment by ranjitjhala** [comment]
Ok let's discuss right now?

**Comment by ranjitjhala** [comment]
This is fine, because in `$k__0[q:=r]` the `q` is **not** in the domain of `k__0` so we can just eliminate the substitution entirely...

**Comment by bmcfluff** [comment]
Eliminate.hs now handles this correctly
