### ISSUE TITLE
Avoid divide-by-zero in the PLE Interpreter

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquid-fixpoint#686]
There was an attempt in #560 to avoid producing expressions in tests that would cause divide-by-zero when simplifying them. This problem seems to have resurfaced [here](https://github.com/ucsd-progsys/liquid-fixpoint/pull/684#issuecomment-1996225631) with a counter-example like:
```haskell
POr
  [ POr
    [ ESym (SL "dymkjhhxgd")
    , ECon (L "emurwzzckkgx" (FTC (TC "Stcdlfq" (dummyLoc) (TCInfo {tc_isNum = False, tc_isReal = False, tc_isString = False}))))
    ]
  , EBin Div (ECon (I 0)) (ECon (R 0.0))
  ]
```
I cannot reproduce the failure, but it is apparent that [the code](https://github.com/ucsd-progsys/liquid-fixpoint/blob/2ba8ecf139b85dd537b100e5f93937a0b5b43684/tests/tasty/Arbitrary.hs#L119-L120) that generates expressions would need to recognize the division by zero when one operand is integer and the other is real.

I do want to ask, however, why is that the simplifier must simplify all divisions of constants, instead of leaving divisions by zero unmodified. Perhaps a better solution is to modify the [simplifier](https://github.com/ucsd-progsys/liquid-fixpoint/blob/2ba8ecf139b85dd537b100e5f93937a0b5b43684/src/Language/Fixpoint/Solver/Simplify.hs#L52-L54) to desist from constant folding in this case (?).

**Comment by ranjitjhala** [comment]
I agree, we should just leave the div-by-zero alone in this case I think!
