### ISSUE TITLE
[cutsolver] Multiple Sorts

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#70]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cutsolver/tests/todo/multiple-sorts.fq

The Ocaml solver accepts it while the Haskell solver rejects it. (It's an excerpt from the fq file that LH generates from https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/tyvar.hs)

**Comment by bmcfluff** [comment]
Addressed by af4e59fc2354be7d690f389060aabae024bb55f6

**Comment by ranjitjhala** [comment]
Wow! Do the previously failing tests now pass?

**Comment by bmcfluff** [comment]
Yes
