### ISSUE TITLE
[cutsolver] "Cut" keyword

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#71]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/a74815085ea63653d179c4a996e82c8c9a140efc/tests/todo/cut-keyword.fq

(excerpt of fq file generated by LH from https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/Class2.hs)

**Comment by ranjitjhala** [comment]
Fixed by dd1ae19f3c0aab7599698615603780923b35f3db (or thereabouts).
