### ISSUE TITLE
[cutsolver] Parse error

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#72]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cutsolver/tests/todo/unexpected-ge.fq

(adapted from ite1.hs.fq)

**Comment by ranjitjhala** [comment]
Fixed by: 86cf3040f523dab4558f178efa75a0583ce99d80

(basically, disable ternary exprs in `e ? e : e` form, require: `if e then e else e`)
