### ISSUE TITLE
fixpoint crashes when using CVC 

### ISSUE THREAD

**Issue by nilehmann** [ucsd-progsys/liquid-fixpoint#728]
Fixpoint crashes when running on the following with cvc4 and cvc5

[calc_cample_point_err.smt2](https://github.com/user-attachments/files/18184905/calc_cample_point_err.txt)

with `fixpoint --solver=cvc4`:
```
Crash!: :1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "Parse Error: Symbol 'Z3_OP_MUL' not declared as a variable"
CRASH: -1 : ""
```

with `fixpoint --solver=cvc5`:

```
fixpoint: fd:14: hPut: resource vanished ([smtlib-backends-process] while sending command "<long string containing the smtlib2 file>" to the solver: Broken pipe
```

The content of the string is:

[error.smt2](https://github.com/user-attachments/files/18184926/error.txt)

Running cvc5 directly on that also results in a error related to `Z3_OP_MUL`

**Comment by ranjitjhala** [comment]
I’ll take a look — am afk atm but is it the case this works with z3?

**Comment by nilehmann** [comment]
yes, it works with z3. I found this when trying to run flux on vtock using cvc5.

**Comment by ranjitjhala** [comment]
Looks like we're just not generating some definitions for the CVC5 prelude, will look into why.

<img width="1297" alt="Screenshot 2024-12-18 at 10 16 47 AM" src="https://github.com/user-attachments/assets/603814bf-7037-4439-9377-8e636d217123" />

**Comment by ranjitjhala** [comment]
@nilehmann is there any string stuff going on in this query? I managed to get it "UNSAFE" instead of crash...

**Comment by ranjitjhala** [comment]
NVM.
