### ISSUE TITLE
[cutsolver] Float Literal

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#74]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cutsolver/tests/todo/float-literal.fq

(excerpt from LH https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/Fractional.hs)

**Comment by ranjitjhala** [comment]
Fixed by 

https://github.com/ucsd-progsys/liquid-fixpoint/commit/1eaf8c2d6db42ae514954b6fdedecf7ff4b88702
