### ISSUE TITLE
[cutsolver] "named expression already defined with this name"

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#75]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cutsolver/tests/todo/overwrite-names.fq

(excerpt from LH https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/Overwrite.hs)

If you change the name of the constant, the test will pass. How do we avoid this kind of name conflict?

**Comment by ranjitjhala** [comment]
@bmcfluff I can fix this (the fix is to just memoize names of function symbols so we don't *define* the same symbol twice in SMT land...

**Comment by ranjitjhala** [comment]
Fixed by https://github.com/ucsd-progsys/liquid-fixpoint/pull/78

**Comment by bmcfluff** [comment]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cutsolver/tests/todo/overwrite-names2.fq

Renaming Set_emp makes it pass.

**Comment by ranjitjhala** [comment]
This test ALSO passes if we replace `FAppTy Set_set X` with `Set_set X`. Wonder why.

**Comment by ranjitjhala** [comment]
@bmcfluff -- what is the original haskell source that generates this .fq file? Can you re-run it? The .fq file **should not** have `FAppTy Set X` it should just have have `Set X`.

**Comment by ranjitjhala** [comment]
1. **NEVER EVER** print out `FAppTy` (however it **is** used internally to denote type application),
2. Port the ocaml `app_of_t` so that it eliminates the `FAppTy` BEFORE converting to Z3,
3. Hide all "set" related stuff inside `Theories.hs` (it should **not** appear in `Serialize.hs`)
4. **LATER** Fix OCAML parser to account for (@(0) @(1)) (type variable application, because now, these are NOT explicit)

**Comment by ranjitjhala** [comment]
This should be addressed by PR #103 

Strangely, all LH tests are passing (hopefully no strange caching taking place!) so I didn't (yet) have to do step 4 above.

**Comment by ranjitjhala** [comment]
@bmcfluff can you check the above (and the original `overwrite.hs` and confirm before we close this?) Thanks!

**Comment by bmcfluff** [comment]
I get a type error in LiquidHaskell:

[35 of 76] Compiling Language.Haskell.Liquid.RefType ( src/Language/Haskell/Liquid/RefType.hs, dist/dist-sandbox-5e5f3bbb/build/Language/Haskell/Liquid/RefType.o ) [Language.Fixpoint.Misc changed]

src/Language/Haskell/Liquid/RefType.hs:977:11:
    Couldn't match expected type ‘Sort’
                with actual type ‘Either FTycon b0’
    In the first argument of ‘fApp’, namely
      ‘(Left $ tyConFTyCon tce c)’
    In the expression:
      fApp (Left $ tyConFTyCon tce c) (typeSort tce <$> τs)
    In an equation for ‘typeSort’:
        typeSort tce (TyConApp c τs)
          = fApp (Left $ tyConFTyCon tce c) (typeSort tce <$> τs)

src/Language/Haskell/Liquid/RefType.hs:979:11:
    Couldn't match expected type ‘Sort’
                with actual type ‘Either a0 Sort’
    In the first argument of ‘fApp’, namely ‘(Right $ typeSort tce t1)’
    In the expression: fApp (Right $ typeSort tce t1) [typeSort tce t2]
    In an equation for ‘typeSort’:
        typeSort tce (AppTy t1 t2)
          = fApp (Right $ typeSort tce t1) [typeSort tce t2]
