### ISSUE TITLE
Sort check fails on application with polymorophic arguments

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquid-fixpoint#77]
The following tests [tests/crash.fq](https://github.com/ucsd-progsys/liquid-fixpoint/blob/950feb7308d525ede2f682b3735779f8f6e93b9b/external/fixpoint/tests/crash.fq) makes fixpoint ast.ml unification fail at [sortcheck_pred](https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/external/fixpoint/ast.ml#L1391).

In short the following expression is bad typed: `foo ([Nil([])]) = Nothing ([])`

**Comment by ranjitjhala** [comment]
I am not surprised, but what is the environment in which it fails? (i.e. types of `foo`, `Nil`, `Nothing` etc.)

**Comment by ranjitjhala** [comment]
Ok, yes, I can see the problem. It is possible to add more special case hacks to support this, but I'd rather we just did it properly in the first place! One question: can you get this to run with the '--native' fixpoint solver?

**Comment by nikivazou** [comment]
What is the `--native` fixpoint solver? 

My code is 

```
constant Nothing : func(1, [FAppTy Maybe  @(0)])
constant Nil     : func(1, [FAppTy List  @(0)])
constant foo     : func(0, [FAppTy List  int; FAppTy Maybe (FAppTy List int)])

qualif Bad(v:Bool) : (foo([Nil([])]) = Nothing([]))

constraint:
  env []
  grd true 
  lhs {VV#F1 : a_aL9 | [true]}
  rhs {VV#F1 : a_aL9 | [foo([Nil([])]) = Nothing([])]}
  id 1 tag [1]
```

And I run it with 

```
./fixpoint.native   -notruekvars -refinesort -nosimple -strictsortcheck -no-gen-qual-sorts  tests/fixme.fq
```

**Comment by ranjitjhala** [comment]
'--native' is the new "pure haskell" version of fixpoint, you can do:

   liquid --native foo.hs

to run it (I think).

   .cabal-sandbox/bin/fixpoint -n fixme.fq

seems to work for the above file...


​
