### ISSUE TITLE
[cutsolver] Sets

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquid-fixpoint#83]
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cutsolver/tests/weird/sets.fq (adapted from LH test MeasureSets.hs.fq)

It passes the Ocaml solver with or without the constant definition, but the haskell solver exhibits two distinct failure modes depending on whether you include the constant.

Related to Issue #75 ?

**Comment by ranjitjhala** [comment]
Notes to self @ranjitjhala:

In ocaml, dig around for `SMT.mkEmptySet`.

Note that 

1. `set_emp(v)` ===> `v = smt_set_emp`
2. `set_empty` ===> `smt_set_emp`

In haskell, we only do (1) and **not** (2).

**Comment by ranjitjhala** [comment]
Commit fdf9461cd9 fixes this. However, it *does not* fix #75 -- but even fixpoint.native crashes with that. Can you confirm which .hs file that comes from?
