### ISSUE TITLE
mappend on non-trivial BindEnvs

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquid-fixpoint#91]
While attempting to implement `partitionN` using the `Monoid` instance of `FInfo`, I recieved the following error.

```
**** ERROR *********************************************************************
**** ERROR *********************************************************************
**** ERROR *********************************************************************
mappend on non-trivial BindEnvs
**** ERROR *********************************************************************
**** ERROR *********************************************************************
**** ERROR *********************************************************************
```

This is caused by the `Monoid` instance for `BindEnv`. From https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Types.hs#L1472

```
instance Monoid BindEnv where
  mempty = BE 0 M.empty
  mappend (BE 0 _) b = b
  mappend b (BE 0 _) = b
  mappend _ _        = errorstar "mappend on non-trivial BindEnvs"
```

It seems that `BindEnv` just contains a hash map. Since `HashMap` has a `Monoid` instance, why not define mappend like this:

```
  mappend (BE s m) (BE t n) = BE (s + t) (m `mappend` n)
```

Failing that, is there some other way to combine two `BindEnv` objects so that the `FInfo` `Monoid` instance can work?

**Comment by ranjitjhala** [comment]
That should work but use 'max s t' instead of 's + t'

**Comment by christetreault** [comment]
I've tried both ways:

```
mappend (BE s m) (BE t n) = BE (s + t) (m `mappend` n)
```

...and the suggested implementation:

```
mappend (BE s m) (BE t n) = BE (max s t) (m `mappend` n)
```

and neither works. For both, I get the following test failures:

```
    neg
      stacks.hs:                  FAIL (2.07s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
      StrictPair1.hs:             FAIL (2.04s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
      record0.hs:                 FAIL (0.91s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
      RecSelector.hs:             FAIL (0.92s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
      wrap1.hs:                   FAIL (1.92s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
```

If I'm understanding the code correctly, it seems that `partition'` carries the original `BindEnv` forward into each partition. Following this train of thought, I tried the following implementation that just accepts the "larger" `BindEnv`:

```
  mappend (BE s m) (BE t n)
     | s < t = BE t n
     | otherwise = BE s m
```

However, I see the same test failures. To rule out my `partitionN` function, I've redefined it as:

```
partitionN :: Int -> F.FInfo a -> [F.FInfo a]
partitionN n fi = [mconcat $ snd $ partition' fi]
```

...which should just partition it, then concat all the partitions back together. With this implementation I still see these issues.

**Comment by ranjitjhala** [comment]
Hmm. Can you commit your changes to "cores" and push and I will take a look?

**Comment by ranjitjhala** [comment]
Better idea: we should NOT have a monoid instance for FInfo (as there are
likely subtle invariants that are being broken).

Instead can you


1. modify Language.Fixpoint.Partition.partition' so that it takes an
   extra `Maybe Int` parameter denoting the number of desired
   partitions (Just n) means make 'n' roughly equal sized partitions,
   and Nothing means just use the old method (no re-grouping).

2. create a new type

   data CPart a = CPart { pws :: [F.WfC]
                        , pcs :: [F.SubC a]
                        }

3. create a monoid instance for `CPart a`


3. change

     partitionByConstraints :: F.FInfo a -> KVComps -> [FInfo a]

​   to​

     partitionByConstraints' :: F.FInfo a -> KVComps -> [CPart a]

   by modifying `mkPartition` as:

     `fi`                ===> `CPart`
     `F.cm = M.fromList` ===> `pcs =`
     `F.ws`              ===> `pws`

4. write a function:

    cpartFinfo :: Finfo a -> CPart a -> FInfo a
    cpartFinfo fi p = fi { F.cm = M.fromList (pcs p), F.ws = pws p }

5. write a new function

     cpartFInfos :: Maybe Int -> FInfo a -> [CPart a] -> [FInfo a]
     cpartFInfos Nothing fi  ps = cpartFinfo fi <$> ps
     cpartFInfos (Just n) fi ps = cpartFinfo fi <$> ps'
       where
         ps'                    = resize n ps

6. where `resize :: Int -> [CPart a] -> [CPart a]` uses the monoid instance
for CPart to regroup into n groups.


Finally, you can change:

     partitionByConstraints :: Maybe Int -> F.FInfo a -> KVComps -> [FInfo
a]
     partitionByConstraints k fi = cpartFinfos k fi .
partitionByConstraints' fi

Does this make sense? If so go ahead and try it, else push your latest
branch and I'll do it.




On Wed, Aug 5, 2015 at 6:10 AM, Ranjit Jhala <rjhala@eng.ucsd.edu> wrote:

> Hmm. Can you commit your changes to "cores" and push and I will take a
> look?
>
> On Aug 5, 2015, at 3:23 AM, Chris Tetreault <notifications@github.com>
> wrote:
>
> I've tried both ways:
>
> mappend (BE s m) (BE t n) = BE (s + t) (m `mappend` n)
>
> ...and the suggested implementation:
>
> mappend (BE s m) (BE t n) = BE (max s t) (m `mappend` n)
>
> and neither works. For both, I get the following test failures:
>
>     neg
>       stacks.hs:                  FAIL (2.07s)
>         Wrong exit code
>         expected: ExitFailure 1
>          but got: ExitSuccess
>       StrictPair1.hs:             FAIL (2.04s)
>         Wrong exit code
>         expected: ExitFailure 1
>          but got: ExitSuccess
>       record0.hs:                 FAIL (0.91s)
>         Wrong exit code
>         expected: ExitFailure 1
>          but got: ExitSuccess
>       RecSelector.hs:             FAIL (0.92s)
>         Wrong exit code
>         expected: ExitFailure 1
>          but got: ExitSuccess
>       wrap1.hs:                   FAIL (1.92s)
>         Wrong exit code
>         expected: ExitFailure 1
>          but got: ExitSuccess
>
> If I'm understanding the code correctly, it seems that partition' carries
> the original BindEnv forward into each partition. Following this train of
> thought, I tried the following implementation that just accepts the
> "larger" BindEnv:
>
>   mappend (BE s m) (BE t n)
>      | s < t = BE t n
>      | otherwise = BE s m
>
> However, I see the same test failures. To rule out my partitionN
> function, I've redefined it as:
>
> partitionN :: Int -> F.FInfo a -> [F.FInfo a]
> partitionN n fi = [mconcat $ snd $ partition' fi]
>
> ...which should just partition it, then concat all the partitions back
> together. With this implementation I still see these issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/91#issuecomment-127773049>
> .
>
>


-- 
Ranjit.

**Comment by christetreault** [comment]
Seems reasonable. I'll give it a shot today.

**Comment by christetreault** [comment]
I've made the changes, things are looking good. I'm reluctant to call this one solved until I can make the updates from issue #93 work for me. That said, I'll continue benchmarking this to see if anything has improved.

**Comment by christetreault** [comment]
With issue #93 closed, all tests pass except the ones from issue  #88. I believe that this issue can be closed.
