### ISSUE TITLE
partition' returns empty list for various files

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquid-fixpoint#93]
For various files, `partition'` is returning `[]`. Due to this, I am seeing the following test failures when using the multithreaded solver:

```
Tests
  Unit
    pos
      kmpIO.hs:                   FAIL (1.02s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      Bar.hs:                     FAIL (0.73s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      ResolveA.hs:                FAIL (0.74s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      bar.hs:                     FAIL (0.77s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      profcrasher.hs:             FAIL (0.79s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      Measures1.hs:               FAIL (0.80s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      ResolveB.hs:                FAIL (0.78s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      datacon-inv.hs:             FAIL (0.73s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      PlugHoles.hs:               FAIL (0.73s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      Foo.hs:                     FAIL (0.81s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      pragma0.hs:                 FAIL (0.69s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      Measures.hs:                FAIL (0.72s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
    parser/pos
      TokensAsPrefixes.hs:        FAIL (0.74s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
```

Additionally, it is very likely that this is happening for negative tests as well, seeing false `ExitFailure 1` that is caused by this issue, rather than the actual issue being tested for.

**Comment by christetreault** [comment]
Some additional background:

At first, I didn't check for this case. I assumed that the system would consider `mempty` as a failure, and was just returning the result. However if you `mconcat []` you get `mempty`, and the system considers this to be Sat.

This only fails 1 of the regression tests so I added this check to `solvePar`

```
   case fis of
      [] -> solveExt c fi
      [onePart] -> solveExt c onePart
      _ -> --stuff
```

which would use the serial solver in this case. However, it has now occured to me that this is shortsighted, and that this is just hiding a bug in the system.  Now `solvePar` throws an exception on the empty list case, and it is clear that this issue is much more pervasive than I initially thought.

**Comment by ranjitjhala** [comment]
Interesting. Will take a look at this ASAP. In the meantime I'm guessing
you can make progress on the other benchmarks?

On Wed, Aug 5, 2015 at 11:20 PM, Chris Tetreault <notifications@github.com>
wrote:

> Some additional background:
>
> At first, I didn't check for this case. I assumed that the system would
> consider mempty as a failure, and was just returning the result. However
> if you mconcat [] you get mempty, and the system considers this to be Sat.
>
> This only fails 1 of the regression tests so I added this check to
> solvePar
>
>    case fis of
>       [] -> solveExt c fi
>       [onePart] -> solveExt c onePart
>       _ -> --stuff
>
> which would use the serial solver in this case. However, it has now
> occured to me that this is shortsighted, and that this is just hiding a bug
> in the system. Now solvePar throws an exception on the empty list case,
> and it is clear that this issue is much more pervasive than I initially
> thought.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/93#issuecomment-128090009>
> .
>



-- 
Ranjit.

**Comment by christetreault** [comment]
Yes, and if I run out of stuff to do there is always the book.

**Comment by ranjitjhala** [comment]
I just pushed a fix for this issue (to the cores branch). Can you take a
look?

(We were getting empty lists when the input FInfo had ZERO constraints...)

Interestingly, like many others, a bug that would have been caught if we
were using LH on itself :)


On Fri, Aug 7, 2015 at 12:33 AM, Chris Tetreault <notifications@github.com>
wrote:

> Yes, and if I run out of stuff to do there is always the book.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/issues/93#issuecomment-128475198>
> .
>



-- 
Ranjit.

**Comment by christetreault** [comment]
I'm seeing no change in behavior. Is this the fix?

https://github.com/ucsd-progsys/liquid-fixpoint/commit/d7d72442e4999c3698c2a4b6dca21678e36cfe4c

**Comment by ranjitjhala** [comment]
Sorry, looks like I forgot to push. (But now I did.)

This is the fix, can you see if it works?

https://github.com/ucsd-progsys/liquid-fixpoint/blob/cores/src/Language/Fixpoint/Partition.hs#L53

Also, how are you running the tests?

**Comment by christetreault** [comment]
I've been using `make test`, however when I do I get this error when the test goes to actually run:

```
cabal exec ./dist/build/test/test -- --smtsolver z3 --hide-successes --rerun-update -p 'Unit/' -j1 +RTS -N1 -RTS
cabal: The program './dist/build/test/test' is required but it could not be
found.
Makefile:65: recipe for target 'test' failed
make: *** [test] Error 1
```

I strongly suspect that this is because of my slightly wonky cabal setup, so I haven't reported it as a bug. As a workaround, I do this:

```
$ cabal exec bash
$ ./dist/build/test/test --smtsolver z3 --hide-successes --rerun-update -p 'Unit/' -j1 +RTS -N1 -RTS
```

for testing the single-threaded implementation or:

```
$ cabal exec bash
$ ./dist/build/test/test --smtsolver z3 --hide-successes --rerun-update -p 'Unit/' -j1 +RTS -N4 -RTS --liquid-opts --cores=4
```

for multithreaded. I kind of like it this way because it makes it easy to tweak the arguments (things like showing success)

**Comment by christetreault** [comment]
...and still no dice. I am getting this trace output though:

`Trace: [flattened] : []`

**Comment by christetreault** [comment]
I just verified that all files that were previously failing are still failing

**Comment by christetreault** [comment]
It looks like your fix works if you don't specify a number of partitions. I'll go ahead and see if I can't apply your fix to `partitonByConstraints'`

**Comment by christetreault** [comment]
OK I've updated partition' to apply the fix to both the Nothing case and the Just n case. I've also cleaned up the code a bit, and deleted a bunch of superfluous stuff.

I re-ran the tests, and now the only failing tests are the five from issue #88.

At this point, I believe that this issue can be closed.
